### ISSUE TITLE
Cannot close some tabs

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#100]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.8-91-g2a8fd30
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
I'm getting the following error in logs:

> StackSidebar::__on_forms_filled(): g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.Eolie.Proxy.Page8" does not exist (3)

The issue appeared with 2 different unrelated websites in the last hour.

**Comment by gnumdk** [comment]
Strange that this DBus item is not here, looks like extension is dead. BTW another bug.

**Comment by gnumdk** [comment]
FIxed.

ps: favicons are dead, so don't report a bug for now ;)
