### ISSUE TITLE
Eolie hits 100% CPU

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#101]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.8-91-g2a8fd30
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
It looks like some recent code is making eolie running at 100% CPU all the time, even when a single static site is open. Let me know if I should bisect it.

**Comment by gnumdk** [comment]
It's already fixed in fact ;)
