### ISSUE TITLE
Possibility to open all bookmarks of a given tag at once

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#102]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.8-91-g2a8fd30
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
On Firefox, one can open all bookmarks of a given tag simultaneously, either via bookmarks toolbar *in just two clicks* or in bookmarks manager via right click (more clicks needed). 
I personally use this feature a lot, it would be super cool to have it in eolie somehow (adding an icon near the tag name? double clicking on the tag? right clicking on it (would be less convenient)?). 
At least adding an icon near the other shouldn't break too much things I guess:
 
![capture d ecran de 2017-06-14 16-25-45](https://user-images.githubusercontent.com/1451988/27137471-5a441706-511e-11e7-94d1-4623c0b4be42.png)

I don't know how many users do that though…

**Comment by bagage** [comment]
Cool, nice work! Small issues though:

1) the popover isn't closed when you hit the button
2) the current tab is not removed and keeps the focus (eg. on Firefox if you hit "open all tabs" on a blank page, it is removed and the focus is given to the first newly opened tab. If you hit "open all tabs" on an existing tab, it is kept but the focus is still given to the first newly opened tab).
3) bookmarks are opened, but not loaded (they are loaded once you select them).

**Comment by gnumdk** [comment]
1) Will fix
2) Will fix
3) Sounds bad for me, I have tags with 200 bookmarks, if user it open and all is loaded at once, his computer is dead.

**Comment by bagage** [comment]
3. Well dunno how firefox handles 30+ bookmarks at once - but maybe loading tabs only when they are a reasonable small amount (10? 20?) could do the trick. 
I believe people "opening multiple tabs at once", won't do that with 200+ items - and indeed in that case it  'll probably kill PC.

**Comment by julianrichen** [comment]
@bagage Firefox warns you if you open more then 30+, and allows you to do it if you click Ok.
