### ISSUE TITLE
Native Masterpassword support

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/eolie#103]
It would be amazing if Eolie integrated [MasterPassword](http://masterpasswordapp.com/) support out of the box with no extension needed. MasterPassword is far superior to every other password manager/sync system and implementing the algorithm should be much simpler than coming up with a secure store, integrating with OS keychains/keyrings, figuring out sync support, etc.

**Comment by gnumdk** [comment]
I don't care, Eolie is a GNOME web browser so I use Freedesktop spec.

**Comment by gnumdk** [comment]
And for your information, password sync is already available with Firefox.
