### ISSUE TITLE
highlight adresses instantly on the adress bar

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/eolie#108]
it would be nice if when clicking on the adress bar the link would be automatically highlighted instead of having to click it 2 times...is more intuitive to me...

**Comment by gnumdk** [comment]
No, it's really annoying when you just want to edit url and others brothers do the same.

**Comment by legacychimera247** [comment]
well you can edit urls by clicking 2 times...

**Comment by gnumdk** [comment]
Yes, but all others brother works like this, if you want selection: Ctrl + L

**Comment by legacychimera247** [comment]
i generally use vivaldi and with one click you get the adress highlighted, with two clicks you can select and edit the url...to me it's more intuitive...other browsers work like you said but i can assure you it's very more handy vivaldi's way :)

**Comment by gnumdk** [comment]
Not for me, if you look at first Eolie version, Eolie was using this behaviour and it's was really horrible for me.
