### ISSUE TITLE
open tabs in the background

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/eolie#109]
sometimes i just open tabs for reading them later, so it would be nice to have an option to open tabs in the background...it's unconvenient to have to change tab everytime...

**Comment by gnumdk** [comment]
Middle Click or Ctrl + Click

**Comment by legacychimera247** [comment]
yes but it would be nice to have that option in the contest menu...

**Comment by gnumdk** [comment]
It exists in context menu as "Open in a new window", I need to rework the menu, it's in my TODO list.

**Comment by legacychimera247** [comment]
nice to know :)
