### ISSUE TITLE
Allow setting default history recording time

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/eolie#111]
well i think the title says it all...it would be nice to have an option to delete browser history and an option to set just a limited amount of time to be recorded (eg. 1 day, 3 days, 5 days, 1 week and so on)

**Comment by gnumdk** [comment]
It exists, in history popover.

**Comment by legacychimera247** [comment]
thanks...anyway it would be nice to have a time limit for recording our history...or maybe it's there and haven't seen it yet?

**Comment by gnumdk** [comment]
You know

**Comment by legacychimera247** [comment]
thanks :) very nice addiction :)
