### ISSUE TITLE
Dark theme: some text areas display unreadable black text on blackish background

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#115]
### Environment
- Eolie version: 0.8-130-gc114110
- GTK+ version: 3.22
- Operating system: Fedora 26

### Bug/Feature

When enabling the dark theme, on some websites, text areas display the text in black, while keeping the background in black-ish. The text is therefore unreadable in such cases.

Here is an example on redhat bugzilla:
![capture d ecran de 2017-06-22 14-40-17](https://user-images.githubusercontent.com/1388961/27434476-1a413918-5759-11e7-90a4-7b93ba705c4e.png)

The same with the text being selected:
![capture d ecran de 2017-06-22 14-40-19](https://user-images.githubusercontent.com/1388961/27434475-1a3f79fc-5759-11e7-8250-b415dbe37cb9.png)

Would there be a CSS or Webkit configuration hack that could solve the problem? I would be happy with forcing Webkit GTK to use the GNOME the light theme (with black text on white background), while having the rest of Eolie using the chosen theme (eg. dark).

**Comment by d9h02f** [comment]
https://github.com/gnumdk/eolie/issues/9

**Comment by gnumdk** [comment]
Not possible to fix.

My guess is that website specify a font color but without settings background color.

**Comment by Gwend4l** [comment]
OK, too bad.

Yes this is indeed website specific. Would really be perfect just to tell webkitgtk to ignore the dark theme, but I guess that it's not possible.
