### ISSUE TITLE
Password prompt for no reason on Nextcloud public shared folder

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#118]
### Environment
- Eolie version: 0.9-3-gb1dffaf
- GTK+ version: 3.22
- Operating system: Fedora 26

### Bug

When I try to access a Nextcloud public shared folder, Eolie asks for a username/password for no reason. On Firefox or Epiphany, the shared folder can be accessed directly.

Example: https://bousse.fr/owncloud/index.php/s/seMNHh682gBTaHU

**Comment by gnumdk** [comment]
No issue here :-/

**Comment by Gwend4l** [comment]
Strange! This is what I have:

![capture d ecran de 2017-06-26 08-50-21](https://user-images.githubusercontent.com/1388961/27527538-932ac0c4-5a4c-11e7-91ab-944abc6ef7ef.png)

And I really don't understand why I only have this with Eolie

**Comment by gnumdk** [comment]
This is not really Eolie, it's a WebKitGTK dialog :-/

**Comment by Gwend4l** [comment]
I thought that too, but I was not sure since I cannot reproduce with Epiphany. Really strange.

**Comment by gnumdk** [comment]
Do you have access to the server? You should be able to get what URI is making Apache asking client for Auth.

**Comment by gnumdk** [comment]
Can you test with a new user?

**Comment by gnumdk** [comment]
@Gwend4l ping?

**Comment by Gwend4l** [comment]
My apologies, I have been very busy with work recently... but I haven't forgotten yet :p

Yes I own the server, so I'll have a look as soon as I have some time!

**Comment by gnumdk** [comment]
pong? :-)
