### ISSUE TITLE
Cannot choose data to be filled in login form

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#119]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.8-105-ge2edde6
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
If you have two logins for the same website, Eolie automatically selects the first one and don't let choose which one you want to actually use. Could be great to have for instance (based on Firefox behavior):
1. No data filled automatically, but once you select data input, text completion with both (or more) available inputs.
2. Contextual menu entry (`Fill login form` which would list available choices).

**Comment by gnumdk** [comment]
Do you have example? It should work since last release.

**Comment by bagage** [comment]
Well, facebook for instance. The second account is not listed at all, even if I enterits username the password is not updated accordingly it seems.

**Comment by gnumdk** [comment]
Duplicated: #113
