### ISSUE TITLE
No undo on URL textentry

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#120]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.8-105-ge2edde6
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
When you modify URL (`ctrl+L`), you cannot hit `ctrl+z` to cancel changes you made. Would be great if modifications were stacked and could be canceled / redone on purpose.

**Comment by gnumdk** [comment]
Yes, may fix #121
