### ISSUE TITLE
Login not filled/saved on some websites

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#122]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.8-105-ge2edde6
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
When login into [Riot website](https://riot.im/app/#/login), Eolie doesn't ask if we'd like to save credentials nor it will use them if some are available. Not sure if this is Eolie or Webkit bug though?

**Comment by gnumdk** [comment]
It's a WebKitGTK issue, «submit-form» signal is not emited for js based forms.

**Comment by gnumdk** [comment]
https://bugs.webkit.org/show_bug.cgi?id=173915
