### ISSUE TITLE
Cannot paste image

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#124]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.8-105-ge2edde6
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
Some webpages (including `new issue` from github ;)), supports pasting images. However this seems not to work with Eolie, eg on gnome-shell:
1. Hit `Ctrl+Screenshot` (will copy a screenshot of the whole screen in clipboard)
2. Hit `Ctrl+V` in github `new issue` body.

Nothing happens, while the image should be copied/uploaded.

**Comment by gnumdk** [comment]
Does it work with epiphany?

**Comment by bagage** [comment]
Looks like it does not.

**Comment by gnumdk** [comment]
So, report upstream -> WebKitGTK
