### ISSUE TITLE
Focus lost on login form

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#125]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.8-105-ge2edde6
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
On [framalistes](https://framalistes.org/sympa/loginrequest), when you give the focus to the user textentry or the password textentry, it automatically "disappears". Actually the focus is given to another textentry in top right corner view "Connexion", which also have user/password entries.

**Comment by gnumdk** [comment]
Same with epiphany, please test with another webkitgtk browser before reporting.

So report upstream ;)

**Comment by gnumdk** [comment]
https://bugs.webkit.org/show_bug.cgi?id=173920
