### ISSUE TITLE
sidebar / tab bar auto hide

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#127]
the tabs sidebar on the left, kinda feels cluttered and part of web page and hence feels like a bit of distraction.

Could you please consider a auto-hide sidebar feature or a button to hide/show the pages as it was planned for epiphany; the sidebar is not even hidden in fullscreen mode.

Please see:
https://jimmac.fedorapeople.org/gnome3/web-page-switching.webm

**Comment by fastrizwaan** [comment]
If we could have Pages button like just we have for "search" on headerbar, it would feel less cluttered. The pages button could show "page counters" -> [Pages (5)]

**Comment by gnumdk** [comment]
It was a really cool idea and I'm now using this as default :-)
