### ISSUE TITLE
right-click close tab? no [X] button to close tabs?

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#128]
Other than middle-click and ctrl+w, both are advanced shortcuts, but using the RMB and LMB mouse buttons we can't close a tab.

Please consider adding [X] to tab on hover, and a right click menu.

THanks

**Comment by gnumdk** [comment]
You are talking of "minimal mode", it's not possible as [x] button will disallow user to select page.

**Comment by fastrizwaan** [comment]
That's right in minimal mode, we can have something like a slide out close button or simply close menu entry in the right click menu for minimal mode only.
