### ISSUE TITLE
Do not exit app when single tab is open with ctrl+w

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#129]
1 start eolie
2. press ctrl+t
3. press ctrl+w twice

1st tab closes, and 2nd tab closes and the application exits.

If single tab is open, do not exit eolie; but bring a new tab instead; this is the most known behavior of browsers.

**Comment by gnumdk** [comment]
Can't understand your report. Do you wan Eolie to close on Ctrl + w (when only one page is opened)?

**Comment by fastrizwaan** [comment]
No, when only 1 page is open and we press ctrl+w, the current page should close but eolie should Open a New page with HOME.

simply: Don't exit when only single page is open.

**Comment by gnumdk** [comment]
Here, it does not exit. See #38

**Comment by fastrizwaan** [comment]
yup, it does not exit. thanks.

**Comment by gnumdk** [comment]
I've done nothing, if it was exiting first time you test, there is a bug somewhere :-/
