### ISSUE TITLE
Strange artifacts in input-text boxes

### ISSUE THREAD

**Issue by cristobaltapia** [gnumdk/eolie#13]
When writing in an input-text box I get a strange behaviour when moving the cursor around. It looks as if I had marked something, but I didn't.

![bildschirmfoto von 2017-04-27 22-18-00](https://cloud.githubusercontent.com/assets/7276493/25502592/865ac652-2b97-11e7-83c9-8294c27e3fa7.png)

Maybe it is a problem with webkit... but what do I know :)

**Comment by Vistaus** [comment]
FWIW, I'm also noticing this in GNOME Web, QupZilla and Vivaldi. Vivaldi uses Blink, QupZilla uses QtWebEngine (which is based on Blink) and Blink is based on WebKit. So yes, I think it's a bug in WebKit (which found its way into Blink/QtWebEngine as well).

**Comment by gnumdk** [comment]
Fixed in WebKitGTK master.
