### ISSUE TITLE
back and forward buttons are disabled on youtube

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#130]
I'm using eolie from flathub.

youtube has auto play feature, when a video ends, it starts playing the next video. When this happens, the [<] button remains disabled, so we can't go back to preview viewed video using the back button; We can access the video using alt+left though.

How to reproduce:

1. go to youtube
2. play a video, and let youtube player continue to play another video or press > in youtube video to go to next video
3. observe the [<] button remains disabled even after the next video is played.

**Comment by gnumdk** [comment]
WebKitGTK bug.

**Comment by gnumdk** [comment]
Need to check ;)

**Comment by fastrizwaan** [comment]
This behavior is also there at google.com when we say search a word, and click on the links, the back button remains disabled, but we can go back to previous page by using alt+left shortcut.

**Comment by gnumdk** [comment]
Can you send me a screencast because can't reproduce.

**Comment by fastrizwaan** [comment]
![screenshot from 2017-07-07 21-16-43](https://user-images.githubusercontent.com/1161682/27965495-9d859830-6359-11e7-80e0-8a608cfb491c.png)


If we click on benevolence, or other meanings, the back/forward buttons remain disabled.

**Comment by fastrizwaan** [comment]
ok, when we switch pages / tabs back, makes the back button active again. try ctrl+tab a few times.
