### ISSUE TITLE
eolie useragent string support to access sites like web.whatsapp.com needs 

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#132]
Hi,

There are many sites which allow only some major web browsers like chrome, firefox, etc. please visit http://web.whatsapp.com to see the list.

Please allow USERAGENT support in eolie for such websites.

Thanks.

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-89-g836a3a4
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.8-200.fc25.x86_64 #1 SMP Thu Jun 29 16:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Not a user agent issue, report this agains WebKitGTK, it's a feature check issue.
