### ISSUE TITLE
ctrl+enter to prefix www. and .com suffix like major browsers

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#134]
Please add the feature of ctrl+enter to prefix www. and .com suffix to url name.

example. google (ctrl+enter) -> www.google.com

Thanks.

### Environment
- Eolie version: 0.9-89-g836a3a4
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.8-200.fc25.x86_64 #1 SMP Thu Jun 29 16:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Not sure about this one, only chrome use this and it's really ugly feature, the www part should be handled by webserver, the .com part is not universal.

On more, here I enter goog => www.google.fr is set by Eolie.

**Comment by fastrizwaan** [comment]
firefox, edge, internet explorer, etc. uses this. Could you please consider as an option in preferences

[x] add www. URL .com => ctrl+enter

google changes google.com (.com domain to country specific domain .fr etc.)  based on regions like google.co.in for India, and google.co.uk for UK etc, it's decided by google, we just need to pass google.com, google does the rest.

thanks.

**Comment by gnumdk** [comment]
Here, doesn't happen in firefox

**Comment by gnumdk** [comment]
Ok, happen with Firefox, don't know why it does nothing the first time I test.
No I don't consider adding an option for that.
IMO, it's really a non useful option that works only for some website but not all. Here "lemonde" give me www.lemonde.com instead of www.lemonde.fr :-1:

**Comment by fastrizwaan** [comment]
you may allow users to set ctrl+enter to set www. + .fr (or other custom domain name) in option, there are other shortcuts also in firefox like  shift+enter for www. + .net.

My point is that the web browser users are familiar with these shortcuts, and familiar behavior makes it easy to switch to a new application. also, it won't make any difference to the ones who are not using ctrl+enter; only those users, basically majority of firefox/chrome/internet explorer users who know this shortcut will be comfortable with eolie; those who don't know this shortcut will anyway won't be using it.

Thanks.

**Comment by d9h02f** [comment]
I doubt more than 0,001% of users of any browser know about this feature, let alone use it. Most websites don't require 'www.', it takes one second to type '.com', and I agree with @gnumdk that it's useless for any website that isn't .com.

**Comment by fastrizwaan** [comment]
why doesn  Internet explorer, microsoft edge, google chrome, chromium, opera, firefox, vivaldi (new yet has all the shortcuts working), have these shortcuts? 

Please see https://www.howtogeek.com/114518/47-keyboard-shortcuts-that-work-in-all-web-browsers/

All major web browsers support ctrl+enter for www. + .com; apart from many other shortcuts

small browsers don't have these shortcuts

eolie want's to be a major browser or just a small browser!?

**Comment by gnumdk** [comment]
just a small browser... For Gnome...

**Comment by gnumdk** [comment]
I'm quite sure if I ask all my users at works (30000 users), 0% will know this shortcuts, they don't know Ctrl+Tab so this one...

**Comment by fastrizwaan** [comment]
OK, your wish about ctrl+enter.

and eolie is fast, like three times faster than firefox in starting up. really love the speed of startup and overall performance, it should not be just for Gnome but for all desktops and OSes.

**Comment by gnumdk** [comment]
Nom, it's Eolie goal: GNOME ans only GNOME

**Comment by gnumdk** [comment]
Closing this one as wontfix, Eolie now does DNS prediction (in settings, on by default), you just enter google. and it will auto complete the .com.
Will not add more.
