### ISSUE TITLE
eolie crashes while typing shivyog at address/location bar

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#136]
eolie 

(eolie:20081): Gtk-CRITICAL **: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
/usr/bin/eolie:57: Warning: gtype.c:4264: type id '0' is invalid
  exit_status = app.run(sys.argv)
/usr/bin/eolie:57: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  exit_status = app.run(sys.argv)
Segmentation fault (core dumped)

### Environment
- Eolie version: 0.9-89-g836a3a4
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.8-200.fc25.x86_64 #1 SMP Thu Jun 29 16:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
It's a segfault so a GTK bug. Here it does not crash.

**Comment by gnumdk** [comment]
On more, bugs reported without last GTK stack (3.24) will be closed by default.

**Comment by fastrizwaan** [comment]
Well how can I update gtk stack without updating fedora to 26? flatpak eolie is 0.9 version only.

**Comment by gnumdk** [comment]
0.9 is last stable
