### ISSUE TITLE
eolie stops loading page at redirecting domain

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#138]
please visit www.shivyog.com it should redict to www.shivyogindia.com but the page does not redirect to new domain with the message, "the page is being redirected"

epiphany properly redirects like other browsers do. thanks.

### Environment
- Eolie version: 0.9-94-gaf5c515
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.5-200.fc25.x86_64 #1 SMP Wed Jun 14 17:17:29 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Adblock is blocking https://freegeoip.net/json/, add an exception.
