### ISSUE TITLE
eolie crashes while typing youtube at location bar

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#139]
eolie

(eolie:7139): Gtk-CRITICAL **: gtk_list_store_iter_next: assertion 'priv->stamp == iter->stamp' failed
Segmentation fault (core dumped)

### Environment
- Eolie version: 0.9-89-g836a3a4
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.8-300.**fc26**.x86_64 #1 SMP Thu Jun 29 20:09:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

i've updated to fedora 26 and recompiled eolie

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
#136
