### ISSUE TITLE
"Report a bug" opens Github in a random (?) Eolie window

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#141]
### Environment
- Eolie version: 0.9-110-g500ce03
- GTK+ version: 3.22
- Operating system: Fedora 26

### Bug

When I have an Eolie window opened and active, and that I choose "Report a bug" in the menu, sometimes it opens the Github page in another Eolie window that I had opened in another workspace.

**Comment by gnumdk** [comment]
Fixed
