### ISSUE TITLE
panel location support for top (which may feel like tabs) , bottom, and/or right side too

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#143]
Could you please allow  panel (sidebar) position to be set on top or bottom and/or on right side also.

If we can allow top/bottom position, this becomes traditional tab like interface; which most users are comfortable with popular browsers liek firefox or chrome. This can enhance usability of eolie and easier switching over to eolie because of familiar interface. As eolie startup is fast (takes 2 seconds to startup, whereas firefox and other popular browsers take 10-15 seconds) and eolie is very lightweight, more distros will make eolie as default browser for its performance and lightness.

Thank you.

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-94-gaf5c515
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.12.0-1.fc27.x86_64 #1 SMP Mon Jul 3 15:45:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
No for this one, WONTFIX.
