### ISSUE TITLE
view menu relocation

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#145]
The view menu, is buried inside "pages" drop down list. it should either be on the header bar or inside "hamburger menu"

especially with "no panel" mode, the trash icon makes it even more difficult to assume that "view" menu is inside this.

![screenshot from 2017-07-11 17-03-15](https://user-images.githubusercontent.com/1161682/28066564-1eee6bf0-665b-11e7-9720-6f78310d7257.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-94-gaf5c515
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.12.0-1.fc27.x86_64 #1 SMP Mon Jul 3 15:45:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
All panel options/actions are linked it the same place, the hamburger is linked to the web page.
So I don't think so.
