### ISSUE TITLE
New private page is hidden in trash or search button

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#146]
I'm surprised at how you're not seeing that Pages button should be separate from view, and not combined with Trash and Search drop down list. A dropdownlist (button list) represent the item before it. Who uses such HIGs?

[new page][drop down] is more appropriate than, the dropdown menu beside "Search icon" or "Trash icon"

Usability Test:
Just ask some other web browser users to 

1. find "New Private Window" 
2. find "Panel modes" 

I can tell you, 100% will not go that search icon nor the Trash icon if it is no panel mode.

Anyways it's your browser, I understand you're designing for yourself and not for community or other users, but IMHO you should really seek other users opinion in usability and do some usability test.

Other users seek
1. usability (lack of shortcuts same with major browsers), 
2. familiarity ( top panel mode like tabs) or 
3. discoverability (new private window, panel view mode misplaced) 

I see a potential in eolie to be a popular web browser, with unique feature sets. like Image and Video download supoort and faster overall performance, hence I"m saying all this.

Regards

![screenshot from 2017-07-11 18-17-24](https://user-images.githubusercontent.com/1161682/28068970-55552ff8-6665-11e7-8178-1f8e9dc037c8.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-94-gaf5c515
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.12.0-1.fc27.x86_64 #1 SMP Mon Jul 3 15:45:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
>A dropdownlist (button list) represent the item before it.

Yes, the dropdown list represent the pages context: new, find, trash, more...

Don't see the issue.
