### ISSUE TITLE
unable to distinguish Private Page from normal page in eolie

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#147]
Please make the private page different by using different header color or image overlay on headerbar like epiphany or chrome. Thanks

epiphany:
![screenshot from 2017-07-11 21-25-57](https://user-images.githubusercontent.com/1161682/28077521-a2febef8-667f-11e7-9b09-cee9fabf21e4.png)

google chrome:
![screenshot from 2017-07-11 21-27-22](https://user-images.githubusercontent.com/1161682/28077653-fe0d5c50-667f-11e7-9c3a-99b748f77186.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-98-g6a2d832
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.8-300.fc26.x86_64 #1 SMP Thu Jun 29 20:09:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Added an overlay in view. Will not modify window look as there is no "private window" in Eolie.
