### ISSUE TITLE
Search bar clearing when typing '/'

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#153]
### Bug
Sometimes, when completing an url on the search bar, and when typing `/`, it result to a search bar clearing.

**Comment by gnumdk** [comment]
Any example? Because I see no reason :-/

**Comment by M5oul** [comment]
I can not reproduce. I remember it happen when typing the `/`.

**Comment by gnumdk** [comment]
A part Ctrl + Shift + / je vois pas :-/

**Comment by M5oul** [comment]
I close for now.
I will reopen If I reproduce.
