### ISSUE TITLE
Full screen videos interfere with full screen mode

### ISSUE THREAD

**Issue by City-busz** [gnumdk/eolie#156]
### Environment
- Eolie version: 0.9
- GNOME/GTK+ versions: 3.24.2/3.22.16
- GNU/Linux distribution: Arch Linux

### Bug 1
1. Enter into full screen mode with F11.
2. Start playing a video (e.g. on YouTube) and switch the video to full screen.
3. Press Esc.
Excepted behaviour: the video is switched back from full screen, but the browser remains in full screen mode.
Actual behaviour: the video is switched back from full screen, and the browser leaves the full screen mode too.

### Bug 2
1. Enter into full screen mode with F11.
2. Start playing a video (e.g. on YouTube) and switch the video to full screen.
3. Press F11.
Excepted behaviour: the video is switched back from full screen, and the browser leaves the full screen mode too.
Actual behaviour: the video remains in a windowed full screen, but the browser leaves the full screen mode.

### Bug 3
1. In normal mode, start playing a video (e.g. on YouTube) and switch the video to full screen.
2. Press F11, and you will see the following crash:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eolie/window.py", line 357, in __on_shortcut_action
    self.unfullscreen()
  File "/usr/lib/python3.6/site-packages/eolie/window.py", line 106, in unfullscreen
    self.disconnect_by_func(self.__on_motion_notify_event)
TypeError: nothing connected to <bound method Window.__on_motion_notify_event of <window.Window object at 0x7fa96af752d0 (eolie+window+Window at 0x29c02b0)>>

**Comment by fastrizwaan** [comment]
Yes, crashes on full screen youtube video player and f11 window fullscreen

How to reproduce:
1. start eolie
2. goto youtube.com
3. start playing a video
4. press "f" key for video fullscreen
5. press f11 for window fullscren
6. Crash!

output:
```
eolie 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eolie/window.py", line 357, in __on_shortcut_action
    self.unfullscreen()
  File "/usr/lib/python3.6/site-packages/eolie/window.py", line 106, in unfullscreen
    self.disconnect_by_func(self.__on_motion_notify_event)
TypeError: nothing connected to <bound method Window.__on_motion_notify_event of <window.Window object at 0x7fba7aa73438 (eolie+window+Window at 0x55c2662fc2c0)>>

```

**Comment by gnumdk** [comment]
For me Bug 1 is not a bug, browser should not unfullscreen  on escape.

**Comment by gnumdk** [comment]
Bug3 seems to be fixed, don't know when...
