### ISSUE TITLE
pthread_setspecific error on exit

### ISSUE THREAD

**Issue by City-busz** [gnumdk/eolie#157]
### Environment
- Eolie version: 0.9
- GNOME/GTK+ versions: 3.24.2/3.22.16
- GNU/Linux distribution: Arch Linux

### Bug
I get the following error every time when I close eolie:
```
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_setspecific': Invalid argument.  Aborting.

**Comment by gnumdk** [comment]
ArchLinux bug, only happend on Arch...

**Comment by City-busz** [comment]
Why does it happen? Do you have any idea?
