### ISSUE TITLE
Should be a hotkey to hide sidebar (tabs-bar)

### ISSUE THREAD

**Issue by fyksen** [gnumdk/eolie#16]
When having two or more browser windows open side by side, it would be useful to have a way to temporary hide side bar.

Example picture showing "problem":
![Example picture](http://i.imgur.com/pcFzieK.png)

Example of navigation:
https://www.youtube.com/watch?v=PwgCGmbGEbg&t=0s

**Comment by gnumdk** [comment]
Even with side bar options? (Right click)

**Comment by fyksen** [comment]
Wow, did not know about right click on side panel. Great work! Would like a shortcut to it doh. Ctrl+alt+(1,2,3) or something?
