### ISSUE TITLE
no panel mode, please reduce space between pages 

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#161]
Too much space between pages

![eolie no panel mode](https://user-images.githubusercontent.com/1161682/28226710-ba1f333e-68f4-11e7-8445-f4c3f63b33b9.png)

This one looks a lot better.

![web-overview](https://user-images.githubusercontent.com/1161682/28226786-00a60cec-68f5-11e7-8a0d-efc5b01c44ef.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-170-g6de2135
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.9-300.fc26.x86_64 #1 SMP Wed Jul 5 16:21:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
The space is calculated by the flowbox. The space in the screenshot is not the minimal space.
