### ISSUE TITLE
split view like page tiling support in eolie - feature request

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#163]
https://vivalditips.com/efficiency/tab-tiling/en

please see this video:
https://www.youtube.com/watch?v=xf28B2YXCuE

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-170-g6de2135
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.9-300.fc26.x86_64 #1 SMP Wed Jul 5 16:21:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Sorry, wont fix. Follow GNOME HIG. It's a confusing feature.
