### ISSUE TITLE
Geolocation API should not be allowed without user permission

### ISSUE THREAD

**Issue by City-busz** [gnumdk/eolie#165]
### Environment
- Eolie version: 0.9
- GNOME/GTK+ versions: 3.24.2/3.22.16
- GNU/Linux distribution: Arch Linux

### Bug
The [Geolocation API Specification](https://dev.w3.org/geo/api/spec-source.html#privacy_for_uas) says that "User agents must not send location information to Web sites without the express permission of the user." Currently Eolie gives this permission unconditionally, therefore not meet the specification. E.g. visit https://www.openstreetmap.org/ and click on the "Show my position" button on the right side.

**Comment by gnumdk** [comment]
Next step: Allowing some site to always be accepted.

**Comment by gnumdk** [comment]
Is this working for you? Here, geolocation is not working with Eolie but is ok with epiphany :-(

**Comment by gnumdk** [comment]
Ok, we need to allow Eolie in Geoclue settings :-(

**Comment by gnumdk** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=101840
