### ISSUE TITLE
window snapping or view splitting not possible!?

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#167]
We can't put the eolie window side by side like we can put other gnome applications, using Super+Left Arrow or Super+Right arrows. 

![screenshot from 2017-07-17 22-19-54](https://user-images.githubusercontent.com/1161682/28279446-235d76bc-6b3e-11e7-9715-4b1ef153ae75.png)

Epiphany (gnome-web) has proper window splitting working like other gnome apps:
![screenshot from 2017-07-17 22-25-12](https://user-images.githubusercontent.com/1161682/28279687-e2cb4ed4-6b3e-11e7-9efa-86e3c30e57eb.png)

### Environment
- Eolie version: 0.9-184-gf725ac8
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.9-300.fc26.x86_64 #1 SMP Wed Jul 5 16:21:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gnumdk** [comment]
Here it works...

**Comment by gnumdk** [comment]
It's not working because your screen width is too small... On more, you are using Gnome Shell like Windows 98 :p What are this horrible min/max buttons!!!
