### ISSUE TITLE
(6) what is this on youtube?

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#168]
When I visit youtube, the page title are prefixed with (6) or (2) or something with (#) where # is number, please see:

![screenshot from 2017-07-17 22-31-49](https://user-images.githubusercontent.com/1161682/28279959-d099f246-6b3f-11e7-9f92-895e1341d459.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-184-gf725ac8
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.9-300.fc26.x86_64 #1 SMP Wed Jul 5 16:21:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by fastrizwaan** [comment]
ok vivaldi is also showing (6); not related to eolie
![vivaldi](https://user-images.githubusercontent.com/1161682/28280512-8ea1d9ba-6b41-11e7-9829-8ffa8394f721.png)

**Comment by gnumdk** [comment]
It's your notification count.
