### ISSUE TITLE
Search and navigation helper doesn't close when closing tab.

### ISSUE THREAD

**Issue by fyksen** [gnumdk/eolie#17]
If you start typing in adress bar in a tab, then ctrl + w, the "search and bookmark navigation helper" dialog box still are up from the previosly closed tab.

Examples:
Starting typing in adressbar:
![Started typing](http://i.imgur.com/jRjS8eO.png)

Just ctrl+w, but navbar is still up.
![navbar still up](http://i.imgur.com/tzpV2x3.png)

**Comment by Vistaus** [comment]
https://github.com/gnumdk/eolie/commit/a704ce0562f4eab7f181141dfdee86b4abfb77e6
