### ISSUE TITLE
Please show Speaker Icon to represent page playing audio

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#170]
![screen-shot-2013-11-05-at-13 40 21](https://user-images.githubusercontent.com/1161682/28281556-21ed3dec-6b45-11e7-9f98-ed34e69a20b3.png)

Please set "speaker icon" overlay in the pages; like in firefox or other browsers to show that this page is making sound. This will help in switching to, stopping or closing such pages when there are multiple pages open. 

if possible please add option to mute that page in the right-click menu. 
![img_5626d106ad0d2](https://user-images.githubusercontent.com/1161682/28281620-5c323be2-6b45-11e7-8d0c-809c7f31c9b2.png)

Thanks.

### Environment
- Eolie version: 0.9-184-gf725ac8
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.9-300.fc26.x86_64 #1 SMP Wed Jul 5 16:21:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gnumdk** [comment]
Linked to #151 .
How can I implement this with minimal panel mode... :-1:

**Comment by F3nd0** [comment]
> How can I implement this with minimal panel mode...

Could overlaying the speaker icon on a translucent favicon work well? (See the rough image below.)

![overlay](https://user-images.githubusercontent.com/30075371/28388371-d55e7132-6cd2-11e7-9b15-e6454c35b348.png)

**Comment by gnumdk** [comment]
Mute is not possible, report to webkitgtk if you want them to add such API.

**Comment by fastrizwaan** [comment]
If we use https://extensions.gnome.org/extension/858/volume-mixer/ extensions and open 2 or more pages which are playing audio like youtube, it does show volume slider
![webkit_audio](https://user-images.githubusercontent.com/1161682/28486693-6a37a9a6-6ea2-11e7-86ef-55910b8696b0.png)

If we can just set the volume to 0% then it is mute.

**Comment by fastrizwaan** [comment]
As can be seen here, I have 2 pages with Vimeo video playing and Youtube video playing together, The volume mixer is showing both WebkitWebProcess, can this be used to mute from eolie?
![eolie-volume](https://user-images.githubusercontent.com/1161682/28486751-4df2b578-6ea3-11e7-8c8c-e27cb4023dc5.png)

**Comment by gnumdk** [comment]
No
