### ISSUE TITLE
make eolie tile follow gnome HIG

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#174]
Hi, 
Just because you have bigger screen, that does not mean you say that others have got smaller screen  https://github.com/gnumdk/eolie/issues/167

Please see Gnome HIG about display compatibility:
https://developer.gnome.org/hig/stable/display-compatibility.html.en

Half-screen snap GNOME HIG
**As a rule of thumb, it should be supported on screens that are 1280 pixels or wider**

My screen resolution is 1366 which is wider than 1280; so please make eolie snap just as epiphany, firefox, and other browsers and gnome applications like nautilus, gedit, etc. do based on Gnome HIG
![screenshot from 2017-07-18 22-55-09](https://user-images.githubusercontent.com/1161682/28330828-9de67acc-6c0c-11e7-9e20-3cb3cb467a61.png)

Thanks.

### Environment
- Eolie version: 0.9-193-g16ffd0c
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.10-300.fc26.x86_64 #1 SMP Wed Jul 12 17:05:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gnumdk** [comment]
Sure it's not working because of maximize and minimize button, remove them, use Gnome Shell as it should and it will work. (I guess)
