### ISSUE TITLE
Address bar popover "bookmarks" make no sense!

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#177]
Populars, Recent, Unclassified makes no sense? Why are they blank? What is Populars? Recent and unclassified make sense for bookmarks, though, but there is nothing why not show "search" in the popover instead of bookmarks?

![screenshot from 2017-07-18 23-35-13](https://user-images.githubusercontent.com/1161682/28332251-c67639aa-6c11-11e7-9920-32d9808fe89f.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-193-g16ffd0c
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.10-300.fc26.x86_64 #1 SMP Wed Jul 12 17:05:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
>Why are they blank?
Because you do not have bookmarks

>What is Populars? 
Bookmarks?

> why not show "search"
Search is in the button at top...
