### ISSUE TITLE
Popover oauth redirection not working totally?

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#178]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
I am not sure where the bug stands, but it works on Epiphany and Firefox so I guess that's something in Eolie.

1. Go on http://overpass-turbo.eu/ in a private navigation page
2. Click on `Load` button in top menu
3. Select `Saved queries (osm.org)` --> this will redirect you to openstreetmap login, OK
4. Login with your account

#### Expected behavior
Saved queries are loaded.

#### Actual behavior
Overpass turbo is stuck on "Loading saved queries from osm.org...", like it didn't receive any response from the popover login. If you click on `Saved Queries (local)` and click back on `Saved queries (osm.org)`, the login popover will appear again.

**Comment by gnumdk** [comment]
Should be fixed ;)
