### ISSUE TITLE
Unnecessary bar

### ISSUE THREAD

**Issue by Vistaus** [gnumdk/eolie#18]
There's a bar with the word Eolie and when clicking on it, it just reveals the menu. But the same menu is already in the upper right corner under the browser icon (where it should be). I don't have this problem in other apps, only in Eolie.

![screenshot from 2017-05-03 16 03 11](https://cloud.githubusercontent.com/assets/1716229/25664237/4c8ddae0-301a-11e7-9fb0-4c29dc102b1f.png)

OS: Solus
DE: Budgie 10.3.1 (latest)
Eolie version: latest Git Master

**Comment by gnumdk** [comment]
Not happening with others GTK apps?

**Comment by Vistaus** [comment]
> Not happening with others GNOME apps?

Nope.

But thanks for fixing this so quickly! Your fix worked liked a charm, no more bar! 😄
