### ISSUE TITLE
open all pages for tag is showing small window like Picture in Picture :-)

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#180]
Is this an expected behavior to load thumbnails over current page when we "open all pages for this tag" ?

![screenshot from 2017-07-18 23-42-02](https://user-images.githubusercontent.com/1161682/28332551-dc56a574-6c12-11e7-98d5-10f690fd0d61.png)

### Environment
- Eolie version: 0.9-193-g16ffd0c
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.10-300.fc26.x86_64 #1 SMP Wed Jul 12 17:05:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gnumdk** [comment]
Yes
