### ISSUE TITLE
no close button for bookmarks?

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#181]
There should be a "close" button to exit the popover, we have to click on some other place which is not nice.
![screenshot from 2017-07-18 23-43-46](https://user-images.githubusercontent.com/1161682/28332705-5ac581b4-6c13-11e7-8202-198d3db46850.png)

### Environment
- Eolie version: 0.9-193-g16ffd0c
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.10-300.fc26.x86_64 #1 SMP Wed Jul 12 17:05:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gnumdk** [comment]
Like all popovers in GNOME...

**Comment by fastrizwaan** [comment]
And no gnome application uses Popover on Address/location bar! Come on, you show "Finished" button on removing a bookmark, why not show "Done" button for ease of use?

**Comment by gnumdk** [comment]
>And no gnome application uses Popover on Address/location bar! 

Maps does...

>you show "Finished" button 

That does not close the popover

>why not show "Done" 

Because it's does not follow GNOME HIG: «Close or Done buttons are not usually required in a popover.»

**Comment by fastrizwaan** [comment]
maps popover is beautiful with a border, eolie looks unpolished
![screenshot from 2017-07-20 17-17-38](https://user-images.githubusercontent.com/1161682/28415954-986413e8-6d6f-11e7-9f14-3cce60fdd1c7.png)

eolie's popover looks cluttered and unkempt
![screenshot from 2017-07-20 17-18-49](https://user-images.githubusercontent.com/1161682/28415969-a39cd858-6d6f-11e7-9017-a09bcd39d09d.png)

Please make the popover pretty, like that of maps and arrangement of items should look visually pleasing.

The size of eolie popover is HUGE, it should allow closing using some button.

**Comment by fastrizwaan** [comment]
why not move the "clear" title button (the red trash button) inside the line-edit and put a close button at top right of popover

**Comment by gnumdk** [comment]
>eolie's popover looks cluttered and unkempt

Just try to resize Eolie to 200x200, it will looks even better :p

**Comment by fastrizwaan** [comment]
LOL, but see that there is too much space between 

`Title                      [URL]`
`Address                 [URL]`

See the Tag Area, full of wasted space 
We can use Google's way of tagging in the bookmarks, also "Remove" and Rename buttons are just redundant and not really required.
![screenshot from 2017-07-20 22-25-34](https://user-images.githubusercontent.com/1161682/28430533-7f02de0a-6d9e-11e7-9600-93b3038f4bb2.png)
![screenshot from 2017-07-20 22-25-48](https://user-images.githubusercontent.com/1161682/28430537-84aa89fc-6d9e-11e7-8960-c011c9623388.png)

here's my mockup
![popover_cute](https://user-images.githubusercontent.com/1161682/28430554-92e26fa8-6d9e-11e7-91a1-2b6683027fc0.png)

**Comment by gnumdk** [comment]
What happen if you have 20 items in tags?
And user needs to know all tags...

**Comment by fastrizwaan** [comment]
Seriously, who needs 20 tags to a single website? Let's pretend that we need 20 tags

Website: Youtube.com
Tags: Entertainment, News, Games, Music, Movies, Fun, Comedy, Jokes, Infotainment, Videos, Timepass (past time), Joy, Religion, Streaming

Even with unrelated tags, I could only imagine, like 15 tags even then they are totally unrelated.

Website: Facebook.com
Tags: Friends, Love, Sharing, Social Media, Work, Hangout place, Fake News, Rumours

Could you please imagine a website which may need more than 5 tags? The more number of Tags, the irrelevant the bookmark becomes.

Anyways, very few people are that organized to "Think about TAGS" and manually type them to bookmark a website.

Also, the tiny [x] in the tag makes the remove button redundant, and clicking on the tag allows renaming.

![20_tags](https://user-images.githubusercontent.com/1161682/28478529-6700e2ce-6e76-11e7-92f2-6dfc1fd14669.png)

Thanks.

**Comment by gnumdk** [comment]
Fixed.
