### ISSUE TITLE
Switching (thin) tab view causes crash

### ISSUE THREAD

**Issue by F3nd0** [gnumdk/eolie#185]
### Environment
- Eolie version: 0.9-204-g113179b
- GTK+ version: 3.22
- Operating system: Linux Jado 4.9.18-gnu-r201703261106-1-grsec #1 SMP PREEMPT Thu Mar 30 06:15:27 -03 2017 x86_64 GNU/Linux

### Bug

Eolie crashes whenever I try to change the tab view. Here is the error output from terminal.
```
Error scanning plugin /usr/lib/epiphany/plugins/libevbrowserplugin.so, /usr/lib/webkit2gtk-4.0/WebKitPluginProcess returned 256 exit status
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eolie/menu_pages.py", line 221, in __on_panel_mode_active
    window.container.set_panel_mode(panel_mode)
  File "/usr/lib/python3.6/site-packages/eolie/container.py", line 275, in set_panel_mode
    self.pages_manager.set_panel_mode(panel_mode)
AttributeError: 'PagesManagerListBox' object has no attribute 'set_panel_mode'
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_setspecific': Invalid argument.  Aborting.
```
It might also be worth noting that the tab sidebar is fixed at a very thin width in this version, at least for me.

![screenshot from 2017-07-19 14-38-42](https://user-images.githubusercontent.com/30075371/28367222-5129f31a-6c90-11e7-8ad4-4fe7c41c8373.png)

**Comment by gnumdk** [comment]
Fixed
