### ISSUE TITLE
Possibility to block JavaScript execution

### ISSUE THREAD

**Issue by F3nd0** [gnumdk/eolie#186]
### Environment
- Eolie version: 0.9-204-g113179b
- GTK+ version: 3.22
- Operating system: Linux Jado 4.9.18-gnu-r201703261106-1-grsec #1 SMP PREEMPT Thu Mar 30 06:15:27 -03 2017 x86_64 GNU/Linux

### Feature
Would it be possible to add a checkbox for blocking JavaScript on a website? I know this is possible with Web (Epiphany), although not through the GUI, and not on a per-website basis. This would provide the users with a simple way to stop non-free software from being executed on their computers (so they can enable it for websites whose code they can trust to be free). Some websites also use a ridiculous amount of JavaScript (often for ill purposes) that slows down the computer, and this would be helpful against that.

**Comment by gnumdk** [comment]
Should be easy to implement, all code is already present in Eolie to do this.

**Comment by F3nd0** [comment]
Sounds good! Perhaps consider separating it from “webdev mode” in dconf, in case that bundles in other features as well? (I can see this being very useful for non-developers also.)
