### ISSUE TITLE
URL suggestions: low-quality first suggestion

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#189]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
Still having a bunch of issues with URL bar. When I type some letters, Eolie **always** suggest me the same first autocompleted link. But due to #171 (thankfully solved since then), I entered once a bad entry `google.ft` instead of `google.fr`. 
Since then Eolie always suggest me `google.ft`, even If I **always** go to `google.fr`.

Not sure how Eolie compute what is the "best" item to be displayed, but maybe a combination of most visited one / most recently visited one should solve the issue.

**Comment by gnumdk** [comment]
It already used moste visited...

**Comment by gnumdk** [comment]
But I'm not sure how work auto-completion internally :-/

**Comment by gnumdk** [comment]
Just added a fix, can you test if it works for you?

**Comment by bagage** [comment]
Well I'm affraid it's worse (or not better at least): it always suggests me `googlef.t` now (yeah, I mistyped that too…).

**Comment by gnumdk** [comment]
My bad :)

**Comment by bagage** [comment]
Wow nice "fix" :P. Thanks!
