### ISSUE TITLE
Back/forward button on mouse acts like regular right click.

### ISSUE THREAD

**Issue by fyksen** [gnumdk/eolie#19]
Back/forward button on mouse acts like regular right click. Should be back and front like epiphany/chrome etc.

**Comment by gnumdk** [comment]
I don't understand :)

**Comment by gnumdk** [comment]
Ah ok, on mouse with many buttons?

**Comment by fyksen** [comment]
My bad! Yes, mouse with back/forward buttons!

**Comment by gnumdk** [comment]
Not sure how it works, do you think it emulates the "back/forward" button from multimedia keyboards?

**Comment by fyksen** [comment]
Hmm, I haven't looked into how back/forward works in Linux, but this is what I found on the arch wiki:

"In most modern applications which use back/forward features, XF86Back is mapped to back and XF86Forward is mapped to forward by default. On most MX mice the thumb buttons resolve to 8 & 9. If your mouse is different, check button numbers using xev and replace the numbers used in the example (b:8 & b:9)."

https://wiki.archlinux.org/index.php/Mouse_buttons
