### ISSUE TITLE
Popover buttons don't close popovers

### ISSUE THREAD

**Issue by F3nd0** [gnumdk/eolie#190]
### Environment
- Eolie version: 0.9-215-ge516487
- GTK+ version: 3.22
- Operating system: Linux Jado 4.9.18-gnu-r201703261106-1-grsec #1 SMP PREEMPT Thu Mar 30 06:15:27 -03 2017 x86_64 GNU/Linux

### Bug
After clicking a headerbar button to bring up a popover, clicking the button again won't close the popover, as is the case with other GNOME apps. Please see the video below for comparison.

![peek 2017-07-21 11-32](https://user-images.githubusercontent.com/30075371/28458185-1dee825c-6e09-11e7-97f0-d3796fb206ec.gif)

**Comment by gnumdk** [comment]
It's already fixed, git pull before reporting ;)

**Comment by F3nd0** [comment]
Aha, sorry! Good job! ':D

**Comment by F3nd0** [comment]
Update: It still doesn't work on the popover from the “new tab”/“search” headerbar button cluster for me.
