### ISSUE TITLE
Regression: no more "open all" button in bookmarks

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#191]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
Since 5ca93b05845de32c75e74c82945a0be194e74f6f, the "open all" buttons in popover bookmarks has disappeared.

**Comment by gnumdk** [comment]
Look better ;)

**Comment by bagage** [comment]
Oooh… got it :)!
