### ISSUE TITLE
unselected URLs should not be "Searched on the Web"

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#194]
How to reproduce:
1. Right click on this https://bugs.webkit.org link (observe that we have not selected any text)
2. select "Search on the Web"
3. We get empty google page

Expected Behavior:
1. unselected URLs should not be given the option to be searched
or
2. search the full unselected URL

Eolie version: 0.9-229-g7b3ff81
GTK+ version: 3.22
Operating system: Linux localhost.localdomain 4.11.10-300.fc26.x86_64 #1 SMP Wed Jul 12 17:05:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Bug/Feature

If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

**Comment by gnumdk** [comment]
Fixed by #196
