### ISSUE TITLE
on closing a page, return to parent or previously active page

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#195]
eolie does not take us back to previous page when we close a page.

How to reproduce
1. Start eolie, google is set as homepage, so it loads
2. in a new tab go to IMDB.com (level 0)
3. in imdb.com select any link (level 1)
4. in the new link select another link (level 2)
5. close page using "trash" icon or ctrl+w

6. we are thrown  back at level 0 (imdb.com) or google (1st page) instead of level 1 (imdb.com's 1st link we clicked)

Expected Behavior:
closing a page should take back to the previous page not randomly show different page

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-235-g53e8599
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.10-300.fc26.x86_64 #1 SMP Wed Jul 12 17:05:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Please do a screencast, can't reproduce here.

**Comment by fastrizwaan** [comment]
Here's the screencast,

https://youtu.be/8dUqDpRS9Ew

1. Google was open in page 1
2. Imdb.com was opened in page 2
3. India top Ten was in page 3
4. Anand movie was in page 4

the order was (open in new page)
imdb-> india-top-ten->anand

but Instead of going back to "India Top Ten" it goes to imdb.com, which is not right.

**Comment by gnumdk** [comment]
It may be fixed ;)

But, Eolie will not go back to the previous active page (I hate this behaviour).

Here Eolie behaviour when closing a page
- Search first brother => first page with same parent
- No brother? Ok, just go to the parent

**Comment by fastrizwaan** [comment]
This is good, brother :-) :+1:
