### ISSUE TITLE
selected text show copy option 2 times

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#196]
Also the 1st copy option does not work!

![doublecopy](https://user-images.githubusercontent.com/1161682/28499469-7ca9be48-6fd4-11e7-9d17-680da9743188.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-235-g53e8599
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.10-300.fc26.x86_64 #1 SMP Wed Jul 12 17:05:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Bad news, #175 is not fixed... Report to webkitgtk as it's not a bug in Eolie.

**Comment by gnumdk** [comment]
Ok, it is fixed.
