### ISSUE TITLE
Password: No popover on facebook

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#204]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
Related to #203, if you have multiple facebook identities and you clear the login input, Eolie does not show the popover.

**Comment by gnumdk** [comment]
Fixed
