### ISSUE TITLE
Password: no data filled in on leboncoin

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#206]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
Even if the list size decreases, there are still some websites where password filling does not work:

- https://www.leboncoin.fr/ then `se connecter` in top right corner. Works OK on https://www.leboncoin.fr/aw?cmd=v&ca=12_s though.

**Comment by gnumdk** [comment]
Reworked all the code. May have introduced new bugs.

Leboncoin not working yet.
