### ISSUE TITLE
garbled screen while rendering gmail

### ISSUE THREAD

**Issue by rohshall** [gnumdk/eolie#209]
### Environment
- Eolie version: 0.9-273-g9ebf774
- GNOME/GTK+ versions: 3.22.17-0ubuntu1
- GNU/Linux distribution: Ubuntu 17.10 (artful)

### Bug/Feature

As the screenshot shows, the gmail page is garbled. After mouseover, that portion of the page gets rendered correctly only to be garbled back again after a few seconds.

![2017-07-27-09 53 03-screenshot](https://user-images.githubusercontent.com/225175/28682621-70e68d1c-72b2-11e7-84e4-c5a942ee459e.png)

**Comment by gnumdk** [comment]
Webkitgtk bug, report upstream.
