### ISSUE TITLE
Adblock doesn't work on youtube.

### ISSUE THREAD

**Issue by fyksen** [gnumdk/eolie#21]
Adblock doesn't work on youtube.com

**Comment by fyksen** [comment]
My bad, I was on a old version of Eolie. Seem to work now.

**Comment by gnumdk** [comment]
No, youtube adblock is not working as it should be down via js. Help is welcome:
https://github.com/gnumdk/eolie-adblock

**Comment by gnumdk** [comment]
Just added a youtube adbloker, seems to work.
