### ISSUE TITLE
JavaScript gets blocked for exceptions on first visit.

### ISSUE THREAD

**Issue by F3nd0** [gnumdk/eolie#214]
### Environment
- Eolie version: 0.9-235-g53e8599
- GTK+ version: 3.22
- Operating system: Linux Jado 4.9.18-gnu-r201703261106-1-grsec #1 SMP PREEMPT Thu Mar 30 06:15:27 -03 2017 x86_64 GNU/Linux

### Bug/Feature
I have set several sites as exceptions to JavaScript blocking. However, when I visit them, JavaScript still gets blocked; they need to be refreshed or reloaded once for the JavaScript to pass. After that, it works normally in the same tab. If the same site is opened again in another tab, the problem repeats. See the video below for illustration. [Tuja Vortaro](http://www.tujavortaro.net/) used as an example site.

![peek 2017-07-29 11-57](https://user-images.githubusercontent.com/30075371/28743919-5655e3ee-7456-11e7-89ec-e4910838ebc0.gif)

(This is a minor issue and only presents a small inconvenience.)

**Comment by gnumdk** [comment]
Setup js blocker on load, exceptions will not work if redirected. No fix possible.
