### ISSUE TITLE
Please use zero transparency for "Titles" of Pages in Popular Pages and View All Pages

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#217]
The page title text backgound is a little transparent hence it is difficult to read the text. Please make it non transparent for better legibility of text. 

Eolie (with transparency; please see 1, 3, and 4)
![screenshot from 2017-07-31 22-49-45](https://user-images.githubusercontent.com/1161682/28789953-e8e0ed54-7644-11e7-92de-ded8d4f2197a.png)

Other browsers have different background color and no transparency for this:
![fast-dial-14](https://user-images.githubusercontent.com/1161682/28789994-0d439aca-7645-11e7-9520-f860a898b74f.jpg)

![screenshot from 2017-07-31 22-42-04](https://user-images.githubusercontent.com/1161682/28789998-116fc83a-7645-11e7-9d8e-6934b3666cc2.png)

![screenshot from 2017-07-31 22-41-56](https://user-images.githubusercontent.com/1161682/28790004-15b647de-7645-11e7-9771-cbefeb7dc4f2.png)

### Environment
- Eolie version: 0.9-294-g824610e
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gnumdk** [comment]
WONTFIX

**Comment by gnumdk** [comment]
Don't see the opacity issue BTW comment on your other bug ;)
