### ISSUE TITLE
Hitting ctrl+z in textentry clear ALL text, no just modification

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#219]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
1. Hit Eolie menu -> Report a bug
2. Start completing bug description
3. Hit Ctrl+z
#### Expected behavior
The text you just entered is removed
#### Actual behavior
All the text is removed.

**Comment by gnumdk** [comment]
Not here...

**Comment by gnumdk** [comment]
Please provide example ;)

**Comment by bagage** [comment]
Here's a video: https://webmshare.com/aoXy6

I'm hitting Ctrl+Z three times in a row. Don't you have the same behavior? :/

**Comment by gnumdk** [comment]
Fixed another issue with form history.

BTW, behaviour is ok, form is empty when Eolie renders the page, it's then filled via JS. 

So, initial state is empty.

**Comment by bagage** [comment]
Well, OK but then I would expect `ctrl+y` to refill the initial text. I mean it should be possible to reapply any `ctrl+z` sequence that was made, eg here I would expect in three `ctrl+y` to restore the final state.

My point is: the initial text can be cancelled (even if I'm not the one who typed it) but not redone. It should be either totally uncancellable or redoable?

**Comment by gnumdk** [comment]
Ctrl + Shift + z
