### ISSUE TITLE
When ctrl+w focus go on next tab, not previously used or the tab in front.

### ISSUE THREAD

**Issue by fyksen** [gnumdk/eolie#22]
Here is an example. I think the focus should land on the tab in front of, instead on the next tab.

![test](http://i.imgur.com/CbsCQwu.gif)

http://imgur.com/a/9O7eR

**Comment by gnumdk** [comment]
And, that the case in Firefox and Chromium.

**Comment by gnumdk** [comment]
But I can understand the issue as I open new tabs next current. Just want to be sure it introduce another issue.
