### ISSUE TITLE
Two logins for one site: only one proposed

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#220]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
So I removed all my passwords again and resynced from scratch Eolie. I can see in logs:

```
pulling {'payload': {'formSubmitURL': 'https://WEBSITE', 'passwordField': 'password', 'usernameField': 'username', 'httpRealm': None, 'timePasswordChanged': 1497202509465, 'id': '{8fe38c55-b437-31d8-81e0-XXX}', 'username': 'bagage', 'hostname': 'https://WEBSITE', 'timeCreated': 1497202509465, 'password': 'MY_PASS'}, 'modified': 1501537604.89, 'id': '{8fe38c55-b437-31d8-81e0-XXX}'}

pulling {'payload': {'formSubmitURL': 'http://WEBSITE', 'passwordField': 'password', 'usernameField': 'username', 'httpRealm': None, 'timePasswordChanged': 1493117679136, 'id': '{cc2b26f1-32ea-4bc5-9ec9-YYY}', 'username': 'admin', 'hostname': 'http://WEBSITE', 'timeCreated': 1493117679136, 'password': 'ADMIN_PASS'}, 'modified': 1497560038.46, 'id': '{cc2b26f1-32ea-4bc5-9ec9-YYY}'}

pulling {'payload': {'formSubmitURL': 'http://WEBSITE', 'passwordField': 'password', 'usernameField': 'username', 'httpRealm': None, 'timePasswordChanged': 1490691994786, 'id': '{1426745b-1978-4b41-b796-ZZZ}', 'username': 'bagage', 'hostname': 'http://WEBSITE', 'timeCreated': 1490691994786, 'password': 'MY_PASS'}, 'modified': 1494273081.65, 'id': '{1426745b-1978-4b41-b796-ZZZ}'}
```

Also in gnome-keyring all 3 entries appear (even if http/https are the same one, maybe another bug). When going on site, only one (username=bagage) is proposed.

**Comment by bagage** [comment]
I've unsync Eolie, then removed passwords from Eolie directly (manage passwords -> remove passwords) + removed `.local/share/Eolie` and `.cache/Eolie`. Closed Eolie, reopened it, resynced and finally waited for full sync.

**Comment by gnumdk** [comment]
Error is first, do not unsync before removing passwords... They will be resynced after...

**Comment by bagage** [comment]
Seems to be fixed when starting from fresh account, cannot reproduce.
