### ISSUE TITLE
Sync: no automatic form filling sometime

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#221]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
For instance on http://linuxfr.org, Eolie does not fill the login form automatically. I still have to click on login entry, then select my username in the popover even if there is only one entry.

**Comment by gnumdk** [comment]
Please remove credrentials ;) Last fix in form handling implies removing all credentials...

**Comment by bagage** [comment]
Yes, I discovered that tiny "issue" - but I already cleared credentials (and everything else). I tried again just now (remove all passwords, unsync, then stop Eolie and `rm -r ~/.local/share/Eolie ~/.config/Eolie`, then opening eolie and resyncing) - but still having the issue.

**Comment by gnumdk** [comment]
Strange, here it works, what is seahorse content?

**Comment by bagage** [comment]
Err… I have 2 entries:

![capture du 2017-08-06 10-27-49](https://user-images.githubusercontent.com/1451988/29001697-ea4e5766-7a91-11e7-8843-b2836cf6760b.png)

**Comment by gnumdk** [comment]
Hmm, do you have tested an old Eolie version, the first password looks like passwords saved before Mozilla Sync support.

**Comment by gnumdk** [comment]
?

**Comment by bagage** [comment]
So just to ensure I tested via a new linux account with no existing data, but the issue is still present (using current master).
Only one entry appears in gnome-keyring but still, Eolie doesn't autofill the login form on http://linuxfr.org.

**Comment by gnumdk** [comment]
Ah ok, it's because the site is http... By design. Just click the login form and you will be allowed ;)

Or better, move to https :-)
