### ISSUE TITLE
no UNDO at address/location/search bar?

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#223]
Just change the URL and press ctrl+z to undo the change. Undo is not working!

### Environment
- Eolie version: 0.9-298-ga43f6e2
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fastrizwaan** [comment]
Maps and Nautilus too (gnome apps with headerbar) has no undo functionality

**Comment by fastrizwaan** [comment]
reported to gtk+ at gnome buzilla, https://bugzilla.gnome.org/show_bug.cgi?id=785787

**Comment by gnumdk** [comment]
Will implement this.
