### ISSUE TITLE
Cannot install flatpak from flathub.org

### ISSUE THREAD

**Issue by rugk** [gnumdk/eolie#225]
### Environment
- Eolie version: n/a
- GNOME/GTK+ versions: GNOME 3.24.2
- GNU/Linux distribution: Fedora 26

### Bug/Feature
I have imported the flathub.org flatpak repo and I can find it in GNOME Software:

![flathubeolie](https://user-images.githubusercontent.com/11966684/29074415-80388076-7c4f-11e7-9f62-4f8906188683.png)

When I click on install, nothing happens.
I previously installed and still update other software from flathub.org via GNOME Software, so generally it works.

**Comment by gnumdk** [comment]
Bug in software, use cmdline...

**Comment by rugk** [comment]
Did not work too? I tried to download the file from the website and install via `flatpak install`. Did not work.

**Comment by gnumdk** [comment]
Will give a look after holidays ;)

**Comment by gnumdk** [comment]
[gnumdk@arch ~]$ flatpak --user install flathub org.gnome.Eolie
Updating: org.gnome.Platform/x86_64/3.24 from flathub
[####################] 9 delta parts, 21 loose fetched; 130105 KiB transferred in 120 seco
Now at 1ae6875f56ba.
Installing: org.gnome.Eolie/x86_64/stable from flathub
[####################] 1 delta parts, 137 loose fetched; 134837 KiB transferred in 121 sec
Installing: org.gnome.Eolie.Locale/x86_64/stable from flathub
[####################] 7 metadata, 4 content objects fetched; 136 KiB transferred in 0 sec
[gnumdk@arch ~]$ flatpak run org.gnome.Eolie

Here it works. Closing...
