### ISSUE TITLE
 No module named 'fxa'

### ISSUE THREAD

**Issue by thomasluquet** [gnumdk/eolie#226]
### Environment
- Eolie version:09-301
- GNU/Linux distribution: Manjaro (Archlinux)

### Bug/Feature
Can't syn with firefox account, Message in log :
`SyncWorker::__push_history(): No module named 'fxa`

**Comment by gnumdk** [comment]
Please ask your distribution forum for such questions....
You are missing python fxa module.

**Comment by thomasluquet** [comment]
Sorry, it is realy not cool at all to put issues without question.
My probleme is for synchronisation with firefox. It don't work and ask me module fxa.
I think it is because manjaro pkg don't install it.
I have just type ` sudo pip install pyfxa` and now it is working.

Thanks for everythings and sorry for my bad english.

**Comment by gnumdk** [comment]
I need an entry about pip3 modules in README.md, if someone wants to enhance this part ;)
