### ISSUE TITLE
Youtube: sound volume reset at maximum on next video

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#227]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
If you watch a video on Youtube (didn't test anything else) and reduce system audio volume, Eolie automatically reset sound volume to maximum on next video played.

**Comment by d9h20f** [comment]
Same thing happens in Epiphany (bug hasn't been fixed for years), so I don't think @gnumdk can fix it.

**Comment by bagage** [comment]
My bad I should have checked (at least it is referenced for latter users here ;)). The Epiphany related bug is [Bug 675217](https://bugzilla.gnome.org/show_bug.cgi?id=675217) which is closed because it is assumed it's a webkit bug, but not sure what's the status from here…
@gnumdk feel free to close if nothing can be done in Eolie - in doubt I prefer to leave this open.

**Comment by gnumdk** [comment]
Yes, but report this to webkit devs ;)
