### ISSUE TITLE
No autofill on twitter when selecting login

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#236]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9-27-g7b8cfb5
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
I know that twitter has a JS login form, but I am unsure it's related. When you go on https://twitter.com/login, at least with multiple identities, when you hit on login field, popover appears and you select your account. But when you select any of them, the form is not actually filled?

Also the "login" button on home page is not doing anything, but the same bug applies to epiphany so it's probably a webkit bug ([reported as 176013](https://bugs.webkit.org/show_bug.cgi?id=176013)).

**Comment by gnumdk** [comment]
A lot of code clean up, please test, I may have break some parts.
