### ISSUE TITLE
Show/Hide pages sidebar button?

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#238]
Why don't we have auto-hide pages sidebar or a show/hide pages bar button, so that we don't have to look at the pages sidebar always?

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.2-50-g1278bd3
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.12.8-300.fc26.x86_64 #1 SMP Thu Aug 17 15:30:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Shortcuts window?

**Comment by gnumdk** [comment]
This make me think that string does not work with RTL :-1:

**Comment by gnumdk** [comment]
<Alt>s in last revision
