### ISSUE TITLE
show/hide pages sidebar using drag or click

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#239]
![howto-close-sidebar](https://user-images.githubusercontent.com/1161682/29833096-e869b354-8d07-11e7-8cb8-476e278e2117.png)

Thank you so much for Alt+S shortcut, would it be possible to have the pages sidebar be hidden using dragging/clicking the splitter. Thanks.

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.2-52-g501ef3b
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.12.8-300.fc26.x86_64 #1 SMP Thu Aug 17 15:30:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
No not really possible as I really do not want to make the seperator bigger.
