### ISSUE TITLE
Feature request: change user agent

### ISSUE THREAD

**Issue by Vistaus** [gnumdk/eolie#24]
Web (Epiphany), the official GNOME browser which is also based on WebKitGTK, has a dconf option to change the user agent. It would be great if Eolie implemented this as well so that I can use the full outlook.com Even if Eolie only implements this in dconf like Web (doesn't have to be a GUI option per se).

**Comment by gnumdk** [comment]
What user agent is needed? I prefer to set user agent on the fly with a blacklist.
Will add an option too.

**Comment by Vistaus** [comment]
Well, basically any user agent that displays the full version of Outlook.com, so Firefox, Chrome, SeaMonkey user agent... doesn't really matter to me which one. As long as I'm able to add it.

**Comment by Vistaus** [comment]
@gnumdk Thanks for the fix! It works like a charm! 😄

**Comment by Vistaus** [comment]
I have no idea what happened, but all of a sudden today outlook.com falls back to the light version again instead of the regular version. Still using Eolie from latest Git Master and latest WebKitGTK update.

**Comment by gnumdk** [comment]
Will check, eolie was always using Firefox UA. So I fix it but maybe first patch was even more broken :)

**Comment by gnumdk** [comment]
Should be ok

**Comment by Vistaus** [comment]
Yup, it's OK now, thanks! :)
