### ISSUE TITLE
show/hide sidebar shortcut F9 instead of alt+s

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#240]
Nautilus has F9 key to hide show sidebar, if eolie uses F9 key then it will be consistent with gnome shortcuts and also it is easy to press F9 key than alt+s combo. Thanks.
![screenshot from 2017-08-29 22-26-52](https://user-images.githubusercontent.com/1161682/29833506-44f852e6-8d09-11e7-8b06-15231ead87c6.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.2-52-g501ef3b
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.12.8-300.fc26.x86_64 #1 SMP Thu Aug 17 15:30:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
:+1:
