### ISSUE TITLE
Install error:  GPG signatures found but none in trusted keyring

### ISSUE THREAD

**Issue by mcclurgm** [gnumdk/eolie#241]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

**BUG MAY BE REJECTED IF MISSING**:

### Environment
- Eolie version: latest download, can't find number in flatpakref
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Fedora 26

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here: https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>
Since updating to Fedora 26 (clean install) I have been unable to install from flatpakref. 
To install, I download from the Github.io page to ~/Downloads and run `sudo flatpak install org.gnome.Eolie.flatpakref`.

It outputs 
```
Installing: org.gnome.Eolie/x86_64/stable
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
```
and then terminates. 

I've done some digging on this issue, and according to a [bug](https://github.com/flatpak/flatpak/issues/421) on the official Flatpak GitHub page, this seems to be an error with improperly signed refs or targeting the wrong Flatpak version. There are similar bugs on [Flathub](https://github.com/flatpak/flatpak/issues/944) and [mypaint](https://github.com/mypaint/mypaint/issues/854) which also demonstrate my issue.

**Comment by gnumdk** [comment]
You tried that: https://github.com/flatpak/flatpak/issues/944#issuecomment-319642720 ?

**Comment by mcclurgm** [comment]
Yes, no effect. I just copy-pasted what they wrote so I added Flathub only, if that matters.

**Comment by gnumdk** [comment]
Closing, please add comment here: https://github.com/flathub/org.gnome.Eolie/issues/2
