### ISSUE TITLE
UserAgent String - safari makes eolie render mobile sites

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#242]
"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/604.1 (KHTML, like Gecko) Version/11.0 Safari/604.1"

youtube and other sites are showing dumbed down, mobile / tablet version of web pages. Please add chrome string like vivaldi:

Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.105 Safari/537.36 Vivaldi/1.92.917.43"

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.2-72-g52a3f62
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.12.9-300.fc26.x86_64 #1 SMP Fri Aug 25 13:09:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
No, it's not a good idea. Here youtube is ok.

**Comment by gnumdk** [comment]
Vivaldi is a Chrome fork using Blink engine. I just removed "Chrome string" from Eolie because new youtube ui was not working.

**Comment by gnumdk** [comment]
Just added Safari string, seems to be better.
