### ISSUE TITLE
can't compile eolie - missing autogen, makefile.am

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#243]
[rizvan@localhost eolie]$ git reset --hard
**HEAD is now at 340b981 Update README.md**
[rizvan@localhost eolie]$ ls
aclocal.m4      config.status  install-sh             po
AUTHORS         config.sub     libtool                py-compile
autom4te.cache  configure      ltmain.sh              python-webextension
ChangeLog       COPYING        m4                     README
compile         data           Makefile               README.md
config.guess    depcomp        Makefile.in            search-provider
config.h        eolie          meson.build            src
config.h.in     eolie.in       meson_post_install.py  stamp-h1
config.h.in~    hooks          missing                subprojects
config.log      INSTALL        NEWS
[rizvan@localhost eolie]$ ./configure 
configure: error: cannot find sources (Makefile.am) in . or ..
[rizvan@localhost eolie]$ 

`[rizvan@localhost eolie]$ cd ~/.build/eolie/; git pull; git reset --hard && ./autogen.sh --prefix=/usr && make -j2 && sudo make install
Already up-to-date.
HEAD is now at 340b981 Update README.md
bash: ./autogen.sh: No such file or directory
`

**Comment by bil-elmoussaoui** [comment]
Eolie now uses meson instead of autotools as a build system

**Comment by gnumdk** [comment]
@fastrizwaan Instructions in README.md
