### ISSUE TITLE
Public comment not shown on Youtube with eolie

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#244]
with gnome-web (epiphany) youtube is showing Public Comment, but with eolie, Public comment field is missing, may be useragent string issue.

epiphany has "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/604.1 (KHTML, like Gecko) Version/11.0 Safari/604.1"

![screenshot from 2017-09-04 19-36-00](https://user-images.githubusercontent.com/1161682/30029821-68d53c8a-91a8-11e7-8010-f0ff3f7799c1.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.2
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.12.8-300.fc26.x86_64 #1 SMP Thu Aug 17 15:30:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by fastrizwaan** [comment]
after changing the UserAgent to "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/604.1 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"

Public comment section is visible.

Please add a way to change USERAGENT string in Preferences, so that  some stupid websites also work. Thanks.

**Comment by gnumdk** [comment]
Here it works, Eolie show public comments...

**Comment by gnumdk** [comment]
Hmm, it works randomly :-(

**Comment by gnumdk** [comment]
Seems to be related to adblocking...

**Comment by gnumdk** [comment]
Fixed by adblock js update.

**Comment by gnumdk** [comment]
Just restart Eolie

**Comment by gnumdk** [comment]
>Please add a way to change USERAGENT string in Preferences
Right click on sidebar item
