### ISSUE TITLE
compile fails: subprojects/po could not read from remote repository 

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#245]
`
[rizvan@localhost eolie]$ meson build

Configuring extension.py using configuration
Cloning into '/home/rizvan/.build/eolie/subprojects/po'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:gnumdk/eolie-po.git' into submodule path '/home/rizvan/.build/eolie/subprojects/po' failed
Failed to clone 'subprojects/po'. Retry scheduled
Cloning into '/home/rizvan/.build/eolie/subprojects/po'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:gnumdk/eolie-po.git' into submodule path '/home/rizvan/.build/eolie/subprojects/po' failed
Failed to clone 'subprojects/po' a second time, aborting

Meson encountered an error in file meson.build, line 41, column 0:
Subproject directory 'subprojects/po' does not exist and cannot be downloaded:
No po.wrap found for 'subprojects/po'
`

**Comment by gnumdk** [comment]
hmm, ok :)

**Comment by gnumdk** [comment]
Should be fixed.

**Comment by gnumdk** [comment]
Does it work? :)

**Comment by fastrizwaan** [comment]
Yes, thanks.
