### ISSUE TITLE
Youtube add Public Comment not visible with adblock enabled

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#246]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.2
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Here it works...

**Comment by gnumdk** [comment]
Ok, eolie-adblock last commit was not pushed.
