### ISSUE TITLE
Pages show video in realtime

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#248]
If you try dash to panel, and hover on a window, we can see realtime video playback in the popover.

Eolie just shows static video snapshots which gives not so useful visual feedback to user
![screenshot from 2017-09-08 22-29-36](https://user-images.githubusercontent.com/1161682/30222730-76d7ab34-94e5-11e7-87ca-dce1e237d5d9.png)

dash to panel as can be seen here, shows realtime video in popover
![screenshot from 2017-09-08 22-29-49](https://user-images.githubusercontent.com/1161682/30222757-91a57496-94e5-11e7-828f-97c31fb3a467.png)

Gnome-shell overview and "workspaces" also show realtime preview of the playing video
![screenshot from 2017-09-08 22-32-50](https://user-images.githubusercontent.com/1161682/30222790-bf6f4dac-94e5-11e7-8932-7afbfb3a1631.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.2
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Dash to panel is Gnome Shell (Mutter). Not possible from an application  POV
