### ISSUE TITLE
ads are visible with blocked ads enabled

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#249]
Please see the screenshot, the ad video is playing and on the right side, there is image ad also visible.
![screenshot from 2017-09-08 23-16-31](https://user-images.githubusercontent.com/1161682/30224306-e117f4b2-94eb-11e7-8762-a3a761b187a2.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.2
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Does not happen here...

**Comment by gnumdk** [comment]
Should be fixed because I restored some previous code... WebKitGTK does not support CSS has() function.

**Comment by fastrizwaan** [comment]
From https://github.com/gnumdk/eolie
   44da44d..a0a809c  master     -> origin/master
Updating 44da44d..a0a809c

Ad is visible in the right side.

![screenshot from 2017-09-12 00-56-48](https://user-images.githubusercontent.com/1161682/30292920-6ffc0554-9755-11e7-9d9d-a372fa779c33.png)

**Comment by fastrizwaan** [comment]
Vivaldi is showing empty ad placeholder on top right, But firefox is properly blocking ads.


![screenshot from 2017-09-12 00-59-35](https://user-images.githubusercontent.com/1161682/30293035-d520d766-9755-11e7-8968-9c6fb2d3cda5.png)

Firefox:
![screenshot from 2017-09-12 00-59-35](https://user-images.githubusercontent.com/1161682/30293043-db9db10e-9755-11e7-9775-503938e82dd2.png)

**Comment by gnumdk** [comment]
Please post video URI, it's a pain to find your videos.

**Comment by gnumdk** [comment]
I do not get ad on the right in youtube :( Even with adblock disabled.

**Comment by gnumdk** [comment]
Ok, got the white area like in vivaldi... Firefox should do the same, it's hard to make a conclusion as ads are randomly added.

Don't understand why it's not blocked for you :-(

**Comment by gnumdk** [comment]
Can you check adblock2.db files, is it empty?

**Comment by fastrizwaan** [comment]
Seems to be fixed. both eolie and vivaldi are showing same thing:

Vivaldi:
![screenshot from 2017-09-15 23-04-06](https://user-images.githubusercontent.com/1161682/30495694-9ff1e040-9a6a-11e7-977e-39b75af4fc2f.png)


Eolie:
![screenshot from 2017-09-15 23-03-20](https://user-images.githubusercontent.com/1161682/30495706-a5ec55a2-9a6a-11e7-8569-e3f8125d2b59.png)
