### ISSUE TITLE
Can't login to google account

### ISSUE THREAD

**Issue by deriherdianto** [gnumdk/eolie#25]
• Eolie version: git version
• Gtk Version: 3.90
• Linux distribution: Archlinux

![screenshot from 2017-05-08 13-15-40](https://cloud.githubusercontent.com/assets/8337409/25792593/9c01ef78-33f1-11e7-946f-f224f5bd65fa.png)

I just got those blank screen

**Comment by fyksen** [comment]
Seems to be a problem with the web-engine. Same happens in gnome-web (epiphany), and gnome settings.

**Comment by gnumdk** [comment]
https://bugs.webkit.org/show_bug.cgi?id=171770
