### ISSUE TITLE
clicking reply in gmail crashes eolie

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#250]
eolie 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eolie/view_signals_handler.py", line 148, in __on_create
    webview = WebView.new_with_related_view(related, self._window)
  File "/usr/local/lib/python3.6/site-packages/eolie/view_web.py", line 65, in new_with_related_view
    view.__init(related, window)
TypeError: __init() missing 1 required positional argument: 'window'

![screenshot from 2017-09-09 22-13-59](https://user-images.githubusercontent.com/1161682/30242025-460cf802-95ac-11e7-9a9c-1560ee17d0e9.png)

In epiphany, it does not crash but open a new page (tab) with the youtube video where the comment has been made.

![screenshot from 2017-09-09 22-15-33](https://user-images.githubusercontent.com/1161682/30242035-79b2db9a-95ac-11e7-8b04-cef645872e2b.png)

### Environment
- Eolie version: 0.9.2
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
Duplicated
