### ISSUE TITLE
Group pages in populars, to reduce clutter

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/eolie#252]
There are many pages inside a single domain we might have visited, but with this populars look cluttered. Could we have pages grouping inside populars so that same domain pages don't cause clutter and destroy the purpose of populars, just like with pages sidebar?

![screenshot from 2017-09-09 22-11-50](https://user-images.githubusercontent.com/1161682/30242050-ef6d3c5e-95ac-11e7-86e9-433dabb82d63.png)

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.2
- GTK+ version: 3.22
- Operating system: Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
I was using "Popular bookmarks" but with this changed, I switch to "Popular pages", thanks for idea ;)
