### ISSUE TITLE
Move translation to Transifex/Weblate/...

### ISSUE THREAD

**Issue by d9h20f** [gnumdk/eolie#254]
Zanata is very difficult to use for translators (everything takes at least three times as many clicks as it should and the site is slow), which shows given that there is only a Dutch translation and a German translation that isn't even finished. Seeing that Lollypop is on Transifex, it would make sense to have Eolie on Transifex, too. Otherwise, [Weblate](https://hosted.weblate.org/) is also a good option.

**Comment by gnumdk** [comment]
Will look at Weblate.

Transifex is not an option, it want me to pay.

**Comment by gnumdk** [comment]
@d9h20f Weblate is not that good, I can't find how to add a project...

**Comment by d9h20f** [comment]
You have to apply for hosting, see "Hosting for free software" https://weblate.org/en/hosting/

**Comment by gnumdk** [comment]
Only one project on Weblate... That why I prefer Zanata (Free as speech) and already planned to migrate Lollypop.

**Comment by d9h20f** [comment]
[Weblate is also free software](https://github.com/WeblateOrg/weblate), and the zero-cost Weblate hosting for other free software projects has [a lot more than one project](https://hosted.weblate.org/projects/). Zanata _really_ sucks. If you move Lollypop to it, Lollypop will lose all translations and translators. Eolie has no translations and no translators because Zanata is impossible to use for translators, even signing up is complicated. Weblate even has a bot that automatically pushes translations to GitHub, so you don't need to do so yourself.

**Comment by F3nd0** [comment]
Transifex makes a very poor option, as the web interface depends on non-libre JavaScript. The only way to contribute translations without running non-libre software is to use a command line client after a sketchy sing-up, which is complex and requires detailed instructions on the project owner's part.

> […] Zanata is impossible to use for translators, even signing up is complicated.

I just tried contributing, and it didn't work. I believe one has to join a language team (and probably the project) before they can contribute, but Zanata makes little to no effort of notifying the user. I think it should be very usable once set up properly, but there's indeed room for improvement. However, I must disagree about the complex sign up. I've found the following steps very simple to follow:

1. Visit “[translate.zanata.org](https://translate.zanata.org/?dswid=-2607)”.
2. Click “Sign Up”.
3. Enter credentials.
4. Visit link from confirmation e-mail.
5. Log in.

As a translator, I find Weblate very nice to use. There is gratis hosting available for libre projects only, and many projects make use of it. It certainly is much more straightforward than Zanata, but I think either is an alright option.

**Comment by d9h20f** [comment]
To be clear, I meant signing up for a project. Creating an account is indeed easy, but that's pretty much where Zanata's usability ends.

**Comment by gnumdk** [comment]
I ask for a Weblate account last week, no response...

**Comment by gnumdk** [comment]
But I don't see the issue with Zanata, you click the project, you click the language, you start translating...

**Comment by gnumdk** [comment]
Done.

**Comment by d9h20f** [comment]
Great, thanks!

**Comment by gnumdk** [comment]
Weblate is just not working, full of internal server error!

Will go back to Zanata if it does not work soon, I can't translate Eolie anymore.

**Comment by gnumdk** [comment]
weblate git repository is now in sync with github (after many error messages while browsing weblate) but nothing happen, it always shows me French as translated. 

Zanata is really easier to use for devs!

**Comment by gnumdk** [comment]
Ok, weblate wants dev to update all translations and not only eolie.pot! Really strange behaviour...
