### ISSUE TITLE
Endless loop opening gmail.com after logging into Firefox Sync

### ISSUE THREAD

**Issue by jhasse** [gnumdk/eolie#258]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

**BUG MAY BE REJECTED IF MISSING**:

### Environment
- Eolie version: 0.9.4 (compiled from master)
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Fedora 26

### Bug/Feature
I've tried to log into Firefox Sync. I saw a message that I need to verify the login by email, then eolie started to open tabs non-stop (I think they were all gmail.com) and crashed with out-of-memory.

**Comment by gnumdk** [comment]
Is it fixed? I remember a bug about endless page open but should be fixed.

**Comment by jhasse** [comment]
Hm ... I've updated to the latest version via `git pull && cd build && sudo ninja install` and now this happens again every time I start Eolie (this time with google.com).

**Comment by gnumdk** [comment]
At startup or after sync setup?

**Comment by jhasse** [comment]
At start with sync already set up.

**Comment by jhasse** [comment]
Works, thank you again :)
