### ISSUE TITLE
Smooth scrolling (not pixel-perfect scrolling)

### ISSUE THREAD

**Issue by jhasse** [gnumdk/eolie#259]
This is the one thing which keeps me using Firefox: Both Firefox and Chrome have smooth scrolling when using the mouse wheel. I'm not sure though if this should be fixed upstream in Gtk+ or Webkit instead.

I've created this Gtk+ bug some months ago, but it hasn't got any attention yet: https://bugzilla.gnome.org/show_bug.cgi?id=774261

Also found this Webkit bug, but I'm not sure if I understand it correctly: https://bugs.webkit.org/show_bug.cgi?id=16123

**Comment by gnumdk** [comment]
It's already available but disabled by default (I really dislike smooth scrolling) and I don't want to add an option in UI.

What I will do (now):
- Enable smooth scrolling if Gtk animations are on
- Add an option to force disabling smooth scrolling in dconf (for me)
