### ISSUE TITLE
Handle openning local file

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#26]
## Env
- Eolie version: git@29164edec86a0e055aad27faf5fbe3b63d643db4
-  GTK Version: 3.24
- GNU/Linux distribution: Fedora 26 Alpha

## Enhancement
Opening local file is not handled.
`file:///` URI is not handled. `http://` is added before.

**Comment by gnumdk** [comment]
I do not really understand why this is needed, never us it in any web browser. More arguments? :)

**Comment by julianrichen** [comment]
> More arguments? :)

* Local static web development (html/css/js pages)
* Image viewer (I don't see why but people do)
* Audio/Video player (Again don't really see why but people do for webm, ogg, flac, mp4, mp3, etc..)
* Other major browsers support it

**Comment by gnumdk** [comment]
The only valid argument is the first one and I don't understand how I miss that... I had already open a local html file in Firefox :-)

**Comment by M5oul** [comment]
When I open a file, it does not open it in Eolie, it open it in default web brower. Firefox on my case.
If I choose Eolie as default web brower, it's infinite loop which open tabs with this file.

**Comment by gnumdk** [comment]
@M5oul should be fixed ;)

**Comment by M5oul** [comment]
Thanks it works perfectly!
