### ISSUE TITLE
Random crash when opening new tab

### ISSUE THREAD

**Issue by TomBous** [gnumdk/eolie#261]
### Environment

- Eolie version: 9.6 (flathub)
- GNOME/GTK+ versions: 3.24.2
- GNU/Linux distribution: Fedora 26

### Bug/Feature

First thank you for you application ! I really like the innovative UI, the DE integration, and the integrated extensions. Clean & simple ;)

The app crashed when opening new tab. Can't seem to find a reproducible step to get the app crashing, but i ran it from terminal and get the following error.

PS : Sorry for the incomplete bug report but i'm not a developer, i'm doing my best :) 
If you need me to do something tell me. 

``` Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/eolie/webview_navigation.py", line 286, in __on_decide_policy
    self.new_page(Gdk.WindowType.SUBSURFACE)
  File "/app/lib/python3.5/site-packages/eolie/webview.py", line 246, in new_page
    webview = WebView.new(self._window)
TypeError: new() missing 1 required positional argument: 'view' 
```

**Comment by gnumdk** [comment]
Already fixed in master.

I guess you were doing a Shift + click on a link (hidden feature opening a page in a popover)

**Comment by gnumdk** [comment]
Will release a fix soon

**Comment by TomBous** [comment]
You're right, that was it ! When i type "shift" by error, wanting to type "ctrl". Thank you !
