### ISSUE TITLE
Add "Copy" selection in Right click Menu

### ISSUE THREAD

**Issue by cgiannakidis70** [gnumdk/eolie#264]
### Environment
- Eolie version: 0.9.7
- GTK+ version: 3.22
- Operating system: Linux christoforos-Lenovo-G50-80 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

How about adding in right click menu a selection to copy highlighted text?

**Comment by gnumdk** [comment]
Are you using git version?

**Comment by gnumdk** [comment]
Was broken in current git master, thanks for report.

**Comment by cgiannakidis70** [comment]
Hi.
Yes.I am using current git master.
