### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by cgiannakidis70** [gnumdk/eolie#267]
### Environment
- Eolie version:0.9.9
- GNOME versions: 3.26.1
Hi
With all respect  I want to suggest the use of badge counter in place of "View all page" counter, like the picture below in dock of ubuntu.I don't know if this is possible or hard to make.This is just a suggestion.

Thank you.
![ubuntu-dock-progress-bar-badge](https://user-images.githubusercontent.com/33185625/32221338-d119dad2-be3d-11e7-9c2f-6e7d034e5889.png)

**Comment by gnumdk** [comment]
Was easy to implement ;)

**Comment by cgiannakidis70** [comment]
OK. Thank you.
But there is an issue with that. The badge counter does not refresh (change) when a window is closed. It increases the number of open windows but not the other way.

**Comment by cgiannakidis70** [comment]
Same thing.Does not decrease.

**Comment by gnumdk** [comment]
Now it's fixed and tested :-)

**Comment by cgiannakidis70** [comment]
Hi again.
Can you use the same badge (colors and shape) on the top bar of Eolie where the "view all pages" counter is?
Thanks.

**Comment by gnumdk** [comment]
No, don't respect GNOME HIG.

**Comment by cgiannakidis70** [comment]
You are right.My mistake.

**Comment by gnumdk** [comment]
But should be an idea to let theme creators to handle this.

**Comment by gnumdk** [comment]
Done.

You can manually configure it with:

$ gedit ~/.config/gtk-3.0/gtk.css

```
.eolie-count-label {
    background-color: red;
    color: white;
    border-radius: 16px;
    min-width: 20px;
    font-weight: bold;
}
```

Feel free to make it look as you want:
https://developer.gnome.org/gtk3/stable/chap-css-overview.html

**Comment by cgiannakidis70** [comment]
Thanks a lot.
