### ISSUE TITLE
ImportError: No module named 'dateutil'

### ISSUE THREAD

**Issue by deikatsuo** [gnumdk/eolie#269]
### Environment
- Eolie version: From Flatpak
- GNOME/GTK+ versions: 3.26/gtk3-3.22.25-1
- GNU/Linux distribution: Archlinux

![screenshot from 2017-11-01 00-29-10](https://user-images.githubusercontent.com/8337409/32239183-6ce8e2d8-be9c-11e7-8c0a-2c985d52fa0b.png)

**Comment by gnumdk** [comment]
Building with fix.
