### ISSUE TITLE
Youtube fullscreen play and sidebar

### ISSUE THREAD

**Issue by cgiannakidis70** [gnumdk/eolie#270]
### Environment
- Eolie version:0.9.9
- GNOME version:3.26.1
- GNU/Linux distribution:

Hi.
You-tube full-screen selection (not Eolie full-screen) after leaving fullscreen with "Esc" or onscreen button the sidebar is appearing even though is unchecked

**Comment by cgiannakidis70** [comment]
Hi.
I 've installed from git and now Eolie crashes or closes when I use "Close page" button.

**Comment by gnumdk** [comment]
with message?

**Comment by cgiannakidis70** [comment]
From terminal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eolie/container.py", line 366, in __on_forms_filled
    result = source.call_finish(result)[0]
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.Eolie.Proxy.Page6" does not exist (3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eolie/container.py", line 383, in __on_forms_filled
    self.close_view(view)
  File "/usr/local/lib/python3.6/site-packages/eolie/container.py", line 228, in close_view
    children.remove(view)
ValueError: list.remove(x): x not in list

**Comment by gnumdk** [comment]
Can you give me step to reproduce?

**Comment by cgiannakidis70** [comment]
Tried again from terminal and I got this:

/usr/local/lib/python3.6/site-packages/eolie/pages_manager_child.py:232: Warning: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
  self.__close_button.get_image().set_from_surface(favicon)
Segmentation fault (core dumped)

**Comment by cgiannakidis70** [comment]
And this:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eolie/pages_manager_child.py", line 124, in _on_close_button_clicked
    self.__window.container.pages_manager.try_close_view(self.__view)
AttributeError: 'PagesManager' object has no attribute 'try_close_view'

**Comment by gnumdk** [comment]
Should be better now. I reworked page management in Eolie so you may find some more issue, please report if any ;)

**Comment by cgiannakidis70** [comment]
OK. I will.
