### ISSUE TITLE
Option to disable search suggestions

### ISSUE THREAD

**Issue by danielwhogan** [gnumdk/eolie#271]
### Environment
- Eolie version: 0.9.9
- GNOME/GTK+ versions: 3.26
- GNU/Linux distribution: Arch

### Bug/Feature
Please add an option to disable search suggestions to the privacy preferences since the suggestions send everything typed into URL bar to the configured search engine.

**Comment by gnumdk** [comment]
As I do not want to add a dedicated option, will use the do not track me option.

**Comment by gnumdk** [comment]
Done, may change my mind later if many users tell me they want DNT and suggestions (strange choice)

**Comment by d9h20f** [comment]
DNT is actually almost meaningless, and can even work against you, so I would just remove the functionality. Barely anyone respects it (e.g. none of the big guys like Microsoft, Google, Facebook, Twitter, Apple, etc respect DNT), and it enlarges your fingerprint. I don't want suggestions, but I don't want DNT either.
