### ISSUE TITLE
Error at launch: "Namespace GtkSpell not available"

### ISSUE THREAD

**Issue by yassinphilip** [gnumdk/eolie#274]
#### OS
 Linux xxxxx 4.4.0-97-lowlatency #120-Ubuntu SMP PREEMPT Tue Sep 19 18:42:00 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### DE
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 1539)

#### GTK
libgtk2.0-0:
  Installed: 2.24.30-1ubuntu1.16.04.2
  Candidate: 2.24.30-1ubuntu1.16.04.2
  Version table:
 *** 2.24.30-1ubuntu1.16.04.2 500
        500 http://mirrors.ircam.fr/pub/ubuntu/archive xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.24.30-1ubuntu1 500
        500 http://mirrors.ircam.fr/pub/ubuntu/archive xenial/main amd64 Packages
libgtk-3-0:
  Installed: 3.18.9-1ubuntu3.3
  Candidate: 3.18.9-1ubuntu3.3
  Version table:
 *** 3.18.9-1ubuntu3.3 500
        500 http://mirrors.ircam.fr/pub/ubuntu/archive xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.18.9-1ubuntu3 500
        500 http://mirrors.ircam.fr/pub/ubuntu/archive xenial/main amd64 Packages

### Bug/Feature

```
# eolie&                                 
[1] 29100
# Traceback (most recent call last):
  File "/usr/bin/eolie", line 25, in <module>
    from eolie.application import Application
  File "/usr/lib/python3.6/site-packages/eolie/application.py", line 18, in <module>
    gi.require_version('GtkSpell', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSpell not available

[1]  + exit 1     eolie

```

**Comment by gnumdk** [comment]
Should be fixed with last package.
