### ISSUE TITLE
Add an option to ungroup tabs

### ISSUE THREAD

**Issue by Binero** [gnumdk/eolie#275]
While grouping the tabs really helps for organisation, when browsing it can be frustrating as we have to click twice to open a tab as opposed to once. 

As such, it would be preferable to have a toggle in the preferences panel that allows the user to not group tabs.

**Comment by gnumdk** [comment]
By design, wont fix. There is enough browsers with tabs.

**Comment by gnumdk** [comment]
@Binero Good news: https://youtu.be/aRVL_T7i5HQ

Found a way to make switch faster. But not compatible with minimal sidebar ;)
