### ISSUE TITLE
Overview mode 

### ISSUE THREAD

**Issue by cgiannakidis70** [gnumdk/eolie#277]
### Environment
- Eolie version: 0.9.9
- GTK+ version: 3.22
- Operating system: Linux christoforos-Lenovo-G50-80 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Hi.
There is an issue with overview mode.Windows closed in overview mode (from close button down right) appear again,after a restart of Eolie.

**Comment by gnumdk** [comment]
Old code because this widget was in first release a sidebar :-)

**Comment by cgiannakidis70** [comment]
Hi.
It is happening again if I close the window in overview without selecting it.
But if  I select it in overview and then close it with the button (bottom right) it is not happening.
And Eolie going crazy if I close all the windows in overview .I can not add or delete one.

**Comment by gnumdk** [comment]
Should be fixed ;)

**Comment by cgiannakidis70** [comment]
When there are more than 2 windows open in overview there is problem.
Look:
1.I have 5 pages open in overview.
2.I quit Eolie.
3.I re-open Eolie.5 pages open.
4.I delete 2 of them with the close button (bottom right), without been selected.
5.I quit again Eolie.
6.I re-open Eolie and again 5 windows are open.

**Comment by gnumdk** [comment]
You were asking for this here: https://github.com/gnumdk/eolie/issues/273#issuecomment-341120719

As I sayed, it now keep windows in cache for 25 seconds

**Comment by cgiannakidis70** [comment]
Hi.
I remember that.
But this issue is something else.
If as I say above delete 2 windows with close button (bottom right) but first I select one by one the pages then after quit and re-open before 25 seconds the total number of open windows will be 2.

**Comment by gnumdk** [comment]
> with close button (bottom right)

Close button should be top right or top left no?

**Comment by cgiannakidis70** [comment]
I do not have problem with that.I like it and at bottom right.

**Comment by cgiannakidis70** [comment]
In overview in each window there is a close button at the bottom right side of it.

**Comment by cgiannakidis70** [comment]
Hi.
I think that you fix it.
It is working as it should now.
Thanks a lot.
