### ISSUE TITLE
Right click on Bookmarks

### ISSUE THREAD

**Issue by cgiannakidis70** [gnumdk/eolie#279]
### Environment
- Eolie version: 0.9.9
- GTK+ version: 3.22
- Operating system: Linux christoforos-Lenovo-G50-80 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Hi.
When  I right click on a bookmark, except from the page that it's loading, another new page is opened.

**Comment by gnumdk** [comment]
Yes, it's a wanted behaviour.

**Comment by gnumdk** [comment]
Right click => open in new page, let popover open
Middle click => open in new page, close popover

**Comment by cgiannakidis70** [comment]
Ok.
Thanks.
