### ISSUE TITLE
Uninstall Eolie on Fedora

### ISSUE THREAD

**Issue by MrReSc** [gnumdk/eolie#280]
### Environment
- Eolie version: 0.9.11
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Fedora 26

How can I unistall eolie? I followed your instructions for the installation on Fedora.

**Comment by gnumdk** [comment]
ninja -C build uninstall

**Comment by MrReSc** [comment]
This doesn't work, I'm afraid.
I did:
```
$ git clone https://github.com/gnumdk/eolie.git
$ cd eolie
$ meson build
$ sudo ninja -C build uninstall
```
Then I get the following:
```
ninja: Entering directory `build'
[0/1] /usr/bin/python3 /usr/bin/meson --internal uninstall
Log file does not exist, no installation has been done.
```
But Eolie is still there and it's working.

**Comment by gnumdk** [comment]
You need to install first...

**Comment by MrReSc** [comment]
Ok, thank's. Not it worked!
