### ISSUE TITLE
Https certificate not matching address : accept risk doesn't work

### ISSUE THREAD

**Issue by nath5394** [gnumdk/eolie#281]
Hello, 

Nice project. 
I was going on a website with a bad certificate : the address is not matching. Wehn I click on Accepter le risque et continuer the page just reload and shows the same.

Nath'

TRANSLATORS:
https://translate.zanata.org/project/view/eolie

### Environment
- Eolie version: 0.9.11
- GTK+ version: 3.22
- Operating system: Linux arsene-lupin 4.9.61-1-lts #1 SMP Wed Nov 8 17:49:38 CET 2017 x86_64 GNU/Linux

### Bug/Feature
If your bug is a rendering bug or a WebKit crash, you should report it here:
https://bugs.webkit.org -> Section WebKit Gtk -> title starting with [GTK]

<Describe your bug here>

**Comment by gnumdk** [comment]
And, with an URI?

**Comment by gnumdk** [comment]
Works with https://wrong.host.badssl.com/

**Comment by gnumdk** [comment]
ping? @nath5394

**Comment by gnumdk** [comment]
Closing, no response.

**Comment by nath5394** [comment]
Hello, I am sorry I forgot this issue. :( the address I wanted to go was the local ip for my Synology NAS, on the 5001 port.

**Comment by gnumdk** [comment]
Fixed ;)

**Comment by nath5394** [comment]
Ah bravo je teste ce soir !! I'll try after work ;)
