### ISSUE TITLE
eolie crashes at times

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/eolie#282]
as the title says Eolie crashes sometimes...this is the output i get from terminal

`** (org.gnome.Eolie:2): CRITICAL **: Unsupported type void
SyncWorker::__push_password(): SyncWorker: missing username`

the "critical" message is repeated multiple times...

just in case is needed i'm on latest fedora with latest eolie :)

**Comment by gnumdk** [comment]
Are you sure you are using pygobject3  3.26.1-1.fc27 (update)?

**Comment by legacychimera247** [comment]
nope...fedora 27 is out tomorrow so i'm still on f26...think the file is the f26 one...

**Comment by gnumdk** [comment]
And you should have backtrace in coredumpctl. Install debug package as asked with:
dnf debuginfo-install eolie

**Comment by gnumdk** [comment]
Ok, so it's normal, it's a segfault in pygobject... Can't do anything about that.

**Comment by gnumdk** [comment]
The output message flood is fixed ;)

**Comment by legacychimera247** [comment]
ok thanks
