### ISSUE TITLE
open page in new tab

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/eolie#283]
when clicking with the right button we have the ability to open a new page, and open a new window...would be nice to have the option to open a new tab, to me it's more faster to open a new tab since the tab area is on the left and always present while the page area is some more click away...

oh and of course a quick way to close them, like an ix when hoovering the mouse...

**Comment by gnumdk** [comment]
Not sure to understand, the sitesbar on the left is too slow to click on? Do you know any browser adding "new tab" in right click menu? You can double click the sitesbar in last master version.

And about close, on the item in the sitesbar? You can resize the sitesbar to get pages (and close button) in last master version.

**Comment by legacychimera247** [comment]
ok i will try to explain better...if i click on a link with the right button i get

1 open link in a new page, which open a page that will appear on the "view all pages" section
2 open link in a new private page, that seems to open a private tab on the sidebar on the left
3 open link in a new window, that open another Eolie window

now, the most handy thing should be "open link in a new page" but that, as said, opens a page on the page view, so you'll have to click on the page view for going back (for example) and anyway open another menù. Would be nice if that would just open a new tab in the sidebar, so it's (to me) pratical and faster, and about the close icon, i know what you mean but i don't want the sidebar to take too much space...

**Comment by gnumdk** [comment]
For closing all group site, you can middle click the site.

**Comment by legacychimera247** [comment]
ok, and for the open in a new tab?

**Comment by legacychimera247** [comment]
so, i've finally understood how the create a new page works...it's grouping tab and create a new tab just when the adress is different...anyway i saw your video on yt about grouping tabs and i think that if implemented can easily answer my question in a positive way...not sure about how fast is to close a page this way but we'll see once is implemented...

**Comment by gnumdk** [comment]
>once is implemented...
Once what is implemented?

**Comment by legacychimera247** [comment]
i was taling about this video... https://www.youtube.com/watch?v=aRVL_T7i5HQ
where the tabs have all the pages inside...that would be nice...

**Comment by gnumdk** [comment]
Ah ok, it's already implemented in master.

**Comment by gnumdk** [comment]
I am closing this one because for me it's fixed:
- New page is always visible if sidebar is resized
- Close is on click on close button

**Comment by gnumdk** [comment]
Reopen if you are not happy with the new feature, will release soon.
