### ISSUE TITLE
open a torrent results in a xdg-portal crash

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/eolie#285]
as the title says when downloading a torrent (a magnet file to be exact) eolie ask me if i want to open that in transmission and if i click on yes xdg-portal crashes and just does nothing

and by the way i even noticed that eolie ask me which app to use every time...would be nice if it could just remember the app without asking...

**Comment by gnumdk** [comment]
The crash and the features request belong to xdg-portal project.
