### ISSUE TITLE
Support adding search engines using mycroftproject.com

### ISSUE THREAD

**Issue by cgraeff** [gnumdk/eolie#286]
Suggestion for enhancement:
The method to add search engines is quite cumbersome, as it requires the user to know a specific search address (I, for instance, don't know how to obtain that address for a given site). If support for adding engines through http://mycroftproject.com/ is implemented, that would be a single click operation, and there are many engines already available.

**Comment by gnumdk** [comment]
Engines using post request are not currently working.
