### ISSUE TITLE
GLib.Error: gtk-css-provider-error-quark: application.css:15:14'min-height' is not a valid property name (3)

### ISSUE THREAD

**Issue by ToxicDragon** [gnumdk/eolie#287]
TRANSLATORS:
https://translate.zanata.org/project/view/eolie

**BUG MAY BE REJECTED IF MISSING**:

### Environment
- Eolie version: 0.9.12
- GNOME/GTK+ versions:
> dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'

> ii  libgtk-3-0:amd64             3.18.9-1ubuntu3.3         amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                 3.18.9-1ubuntu3.3         amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common              3.18.9-1ubuntu3.3         all          common files for the GTK+ graphical user interface library
ii  libgtk2-perl                 2:1.2498-1                amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2.0-0:amd64            2.24.30-1ubuntu1.16.04.2  amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                2.24.30-1ubuntu1.16.04.2  amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-common             2.24.30-1ubuntu1.16.04.2  all          common files for the GTK+ graphical user interface library`
- GNU/Linux distribution: elementaryOS

### Bug/Feature
When starting eolie, the following error occurs:
> christian@capricornus-elementary:~$ eolie

> Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eolie/application.py", line 178, in do_startup
    self.__init()
  File "/usr/lib/python3.6/site-packages/eolie/application.py", line 363, in __init
    cssProvider.load_from_file(cssProviderFile)
GLib.Error: gtk-css-provider-error-quark: application.css:15:14'min-height' is not a valid property name (3)`

Eolie is immediately closed.

Used this ppa: https://launchpad.net/~gnumdk/+archive/ubuntu/eolie

**Comment by ToxicDragon** [comment]
Update: This error also occurs when I natively build from git. While compiling, the following Warning may lead to the cause:
> meson build

> The Meson build system
Version: 0.43.0
Source dir: /home/christian/Downloads/eolie
Build dir: /home/christian/Downloads/eolie/build
Build type: native build
Project name: eolie
Native C compiler: cc (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Message: Looking for dependencies
Message: Found python3 binary
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.48.2
Native dependency gobject-introspection-1.0 found: YES 1.46.0
Native dependency gtk+-3.0 found: YES 3.18.9
Message: Compiling resources
Configuring AboutDialog.ui using configuration
Native dependency glib-2.0 found: YES 2.48.2
WARNING: GLib compiled dependencies do not work reliably with 
the current version of GLib. See the following upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=774368
Message: Compiling schemas
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Message: Making a .desktop file
Message: Preparing appdata
Message: Making a list of icons
Native dependency webkit2gtk-web-extension-4.0 found: YES 2.18.3
Native dependency pygobject-3.0 found: YES 3.20.0
Native dependency python3 found: YES 3.5
Configuring pythonloader.c using configuration
Configuring extension.py using configuration
Submodule 'subprojects/po' (https://github.com/gnumdk/eolie-po.git) registered for path 'po'
Cloning into 'subprojects/po'...
remote: Counting objects: 660, done.
remote: Compressing objects: 100% (145/145), done.
remote: Total 660 (delta 178), reused 98 (delta 66), pack-reused 448
Receiving objects: 100% (660/660), 365.77 KiB | 318.00 KiB/s, done.
Resolving deltas: 100% (510/510), done.
Checking connectivity... done.
Submodule path 'po': checked out 'ca0abf01e39c0faa9bc03d4a68dbb05944e61212'

Executing subproject po.

Project name: eolie-po
Message: Update translations
Build targets in project: 8

Subproject po finished.
Configuring eolie-sp using configuration
Configuring org.gnome.Eolie.SearchProvider.service using configuration
Message: Preparing init file
Configuring eolie using configuration
Program meson_post_install.py found: YES (/usr/bin/env python3 /home/christian/Downloads/eolie/meson_post_install.py)
Build targets in project: 8
Found ninja-1.8.2 at /usr/bin/ninja

**Comment by gnumdk** [comment]
GTK 3.18 is not supported anymore.
