### ISSUE TITLE
Translation is locked

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/eolie#32]
The translation on Zanata is locked so no one can translate Eolie right now. Is this intentional?

**Comment by gnumdk** [comment]
No idea how it works, no request like transifex?

**Comment by gnumdk** [comment]
0.3 is not read only here

**Comment by gnumdk** [comment]
What is your username?

**Comment by d9h02f** [comment]
Username "pub". When I try to translate, there's a red lock at the top left which says "This project-version is readonly. It cannot be edited." on mouseover.

Actually I think I first need to request to join a translation team, apparently they're sitewide instead of per project like on Transifex. I'll get back to you if that solves the problem.

**Comment by gnumdk** [comment]
What language would you want to translate?

**Comment by d9h02f** [comment]
Dutch

**Comment by gnumdk** [comment]
Should be ok ;)

**Comment by d9h02f** [comment]
Thanks, it's working now!
