### ISSUE TITLE
Double-click in empty area to open a new tab

### ISSUE THREAD

**Issue by jhasse** [gnumdk/eolie#33]
### Environement
- Eolie version: 0.4

### Feature
It would be great if I can open a tab by double-clicking anywhere in the empty area of the side bar.

**Comment by gnumdk** [comment]
That's a cool idea ;)

**Comment by brunelli** [comment]
@gnumdk I believe this commit made the right click menu stop working on the panel.

**Comment by gnumdk** [comment]
@brunelli No, the menu was moved to toolbar menu because many users was unable to discover it.

**Comment by brunelli** [comment]
Oh, I see... I just saw your comment on the reddit post and, as it wasn't working, came here to open a bug, and then I found this and thought ot might be related. Thanks for the answer.
