### ISSUE TITLE
Closing last tab behavior?

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#38]
### Environement
- Eolie version: Flatpak 0.4
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Debian

### Bug/Feature (yeah I cannot tell which one actually!)

When you close the latest tab, Eolie closes it and replace it with default tab instead. Usually (Chromium, Firefox, don't know for others), on last tab close, browsers exit. 
I don't feel it's necessary a bug, but would you mind clarifying your choice about this behavior?

PS: If that's the intended behaviour, at least it would be great to not close/open the tab if we already are on the default tab. Because it looks strange as it - but it's just my feelings here!

PS2: also, we cannot close/quit the window anyway. Even `ctrl+q` doesn't quit, so you have to use `alt+f4`. Most GNOME applications handle `ctrl+q` to quit I believe?

A part of that, Eolium looks great and will probably replace Firefox for me very soon :) Good work!

**Comment by gnumdk** [comment]
For me it make sense that closing a page/tab does not close the application.
