### ISSUE TITLE
Firefox sync: store/use passwords?

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#39]
### Environement
- Eolie version: Flatpak 0.4
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Debian

### Bug/Feature
After taking a look at `mozilla_sync.py`, it looks like passwords *are* fetched from Mozilla Sync server. However it seems that we cannot neither see them nor use them to autocomplete forms on website? 
I only use the Flatpak version so maybe there is a limitation on it (I have *Installing seahorse will allow you managing your passwords* tips if it matters) - what should we be able to do with passwords fetched from Mozilla Sync as of today?

**Comment by gnumdk** [comment]
Eolie does not sync password, but it's wanted.

**Comment by gnumdk** [comment]
Form autocomplete isn't working since recent release, will fix it.
