### ISSUE TITLE
Onhover webpage url statusbar

### ISSUE THREAD

**Issue by julianrichen** [gnumdk/eolie#4]
It would be nice if users could see the url they are hovering over both for usability and security.

Example, bottom left corner:
![url-tooltip](https://cloud.githubusercontent.com/assets/58045/22717359/940a8d90-ed68-11e6-9825-60f6c6945a7a.png)

**Comment by gnumdk** [comment]
Was done by in titlebar. But was just an easy solution.

Just implemented Firefox/Chrome solution, was easy finally. Sad Epiphany is broken (label is not moving away from links)
