### ISSUE TITLE
Eolie not available in the default browser dropdown menu in GNOME Control Center > Details.

### ISSUE THREAD

**Issue by CopperBezel** [gnumdk/eolie#40]
### Environment
- Eolie version: 0.4 built from git
- GNOME/GTK+ versions: GNOME 3.24.2
- GNU/Linux distribution: Ubuntu 17.04

### Bug/Feature
Eolie wasn't available in my list of installed browsers under GNOME Control Center > Details to set as the default browser. Adding Eolie manually to ~/.local/share/applications/mimeapps.list worked as expected, and xdg-open launches web addresses in Eolie, so the only issue seems to be that it isn't listed or recognized as a recommended app for html / http. 

I don't know whether my platform or choice of installation method might be responsible for the bug, and it was a minor workaround on my end, but seemed worth noting!

**Comment by gnumdk** [comment]
Ok, works here since the start (Fedora and ArchLinux) so for me the issue is in Ubuntu.

Does it works with my flatpak app?

**Comment by CopperBezel** [comment]
Ah, I see. Yes, it looks like it does work with the flatpack build, so it's only when building from source on Ubuntu. (How odd, but makes it a very minor bug indeed.) I repeated the process on my other machine (running the same Ubuntu version) and got the same result, so it seems to be repeatable.

**Comment by M5oul** [comment]
Works fine on my side with Fedora.

**Comment by gnumdk** [comment]
update-desktop-database fix the issue here on Ubuntu 17.04

**Comment by CopperBezel** [comment]
Thanks for testing this. I just tried update-desktop-database and it didn't work on my end, which I guess means it's not even an Ubuntu bug, just something weird in my configuration somewhere I wouldn't know how to tease out and very unlikely to come up for anyone else.
