### ISSUE TITLE
No crypto module for Firefox Sync

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#41]
### Env
- Eolie version: 0.4.0@10cf28ed16943b20862df6139db054155ae94140
- GNOME version: 3.24
- GNU/Linux distribution: Fedora 26 Alpha

### Bug

```bash
Application::init(): No module named 'Crypto'
```

**Comment by gnumdk** [comment]
You are missing deps, check https://github.com/flathub/org.gnome.Eolie/blob/master/org.gnome.Eolie.json for deps.
And if you have motivation to update README.md with all deps and manual installation instructions ;)
