### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#45]
### Env
- Eolie version: 0.4.0@10cf28ed16943b20862df6139db054155ae94140
- GNOME version: 3.24
- GNU/Linux distribution: Fedora 26 Alpha

### Bug

Consulting https://forum.duniter.org result with:
```bash
Connection is not secure
The signing certificate authority is not known
This does not look like the real https://forum.duniter.org/.
Attackers might be trying to steal or alter information going to or from this site (for example, private messages, credit card information, or passwords).
Accept Risk and Proceed
```

It's a wildcard certificate recently generated.

**Comment by gnumdk** [comment]
WebKitGTK bug as it's the same with Epiphany. Can you report this to https://bugs.webkit.org ?

**Comment by gnumdk** [comment]
https://tools.ietf.org/html/rfc6125

>the wildcard character '*' SHOULD NOT be included in presented identifiers but MAY be checked by 
>application clients (mainly for the sake of backward compatibility with deployed infrastructure)

You should not use such certificate, my certificate is for domain.org and it is working for all subdomain.
