### ISSUE TITLE
Add animation to the tab center 

### ISSUE THREAD

**Issue by somas95** [gnumdk/eolie#46]
### Environement
- Eolie version: 0.4
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Archlinux

### Feature

Now the tab center expands in 0 seconds, and after the cursor leaves it it has a delay of ~1sec. before collapsing 

An easing animation would improve the user experience while being aesthetic

**Comment by gnumdk** [comment]
Help is welcome, not sure how to do this with GTK.

**Comment by somas95** [comment]
Do you know if gtk support css animations? I know how to do it that way

**Comment by gnumdk** [comment]
GTK support animations on widget show/hide but not for size request changes (I may be wrong)

BTW, fixed but manually. If someone know how to do this with CSS, please send me a pull request :)
