### ISSUE TITLE
Ortography language selector

### ISSUE THREAD

**Issue by somas95** [gnumdk/eolie#48]
### Environement
- Eolie version: 0.4
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Archlinux

While Gnome supports various dictionaries for different languages, Eolie uses the default dictionary. It's common write in different languages on different webs, so the ability to select the desired dictionary would be great

Geary does this with a button, maybe in this use case a submenu in the context menu is a better option
![captura de pantalla de 2017-05-31 16-28-33](https://cloud.githubusercontent.com/assets/8913975/26636970/7e2688ee-461e-11e7-830e-0402a2970423.png)
![captura de 2017-05-31 16-36-272](https://cloud.githubusercontent.com/assets/8913975/26637327/7856c3ba-461f-11e7-8f66-a26be4e26b37.png)

**Comment by gnumdk** [comment]
Done
