### ISSUE TITLE
Some issues with "checkinstall"

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#50]
### Environement
- Eolie version: git master 9d15548
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Debian unstable

### Bug/Feature
I followed instructions for Ubuntu to install Eolie via checkinstall but I ran into 2 issues.

#### 1. Invalid version

```
# checkinstall

checkinstall 1.6.2, Copyright 2009 Felipe Eduardo Sanchez Diaz Duran
           This software is released under the GNU GPL.



*****************************************
**** Debian package creation selected ***
*****************************************

*** Warning: The package version "0.6
0.6
0.6" is not a
*** Warning: debian policy compliant one. Please specify an alternate one
```
Not a big one but I thought it would be better to report it anyway

#### 2. checkinstall failed due to missing directories.

Basically I had various errors:

```
 /bin/mkdir -p '/usr/local/lib/python3.5/site-packages/eolie/'
/bin/mkdir: impossible de créer le répertoire « /usr/local/lib/python3.5/site-packages »: Aucun fichier ou dossier de ce type
Makefile:424 : la recette pour la cible « install-appPYTHON » a échouée
```
Which was fixed by manually running:
```
# mkdir -p /usr/local/lib/python3.5/site-packages
```

And latter:
```
libtool: install: chmod 644 /usr/local/share/eolie/webkitextension/libpythonloader.a
libtool: install: ranlib /usr/local/share/eolie/webkitextension/libpythonloader.a
ranlib: could not create temporary file whilst writing archive: No more archived files
Makefile:442 : la recette pour la cible « install-webkitextensionLTLIBRARIES » a échouée
```
Which was fixed (thanks to [this article](https://squeakyspacebar.wordpress.com/2012/07/10/ranlib-issue-while-using-checkinstall/)) by the same thing:
```
# mkdir -p /usr/local/share/eolie/webkitextension
```

Don't know if it's specific to debian (which is not the one you support) but at least it may help others to figure this out.

- [ ] Fix version issue (n°1)
- [ ] Fix folder creation issue (n°2)

**Comment by gnumdk** [comment]
No idea how checkinstall, intructions comes from Lollypop.
If someone can help fixing this issue.

**Comment by bagage** [comment]
Regarding the version issue, the problem is related to `LT_INIT` invokation in `configure.ac`. But I'm not confident with autotools so I won't be able to help much on this issue for now.

**Comment by gnumdk** [comment]
For version issue, it will be fixed as soon Eolie hit 0.9.0 ;)

**Comment by bil-elmoussaoui** [comment]
@gnumdk Why not using Meson instead of Autotools? I can create a PR that introduces the move to Meson for both Lollypop & Eolie if you want :)

**Comment by gnumdk** [comment]
I want :-)
