### ISSUE TITLE
Eolie not resizing half-screen

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#52]
### Environement
- Eolie version: git master 9d15548
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Debian unstable

### Bug/Feature
The same bug exists for Geary which also uses Webkit so I don't know if it's related to it, but when you resize Eolie with `ctrl+shift+left arrow` or `ctrl+shift+right arrow`, Eolie does not resize.
However, using [Shell tile](https://extensions.gnome.org/extension/657/shelltile/) extension which allows to place/resize window on corners, we can force Eolie to take half screen. Would be really nice to have this sweet feature imo :).
I'm running on a 1920x1080p screen if it matters.

PS: sorry for opening many bugs!

**Comment by gnumdk** [comment]
In fact, it does not work if Eolie is maximized.

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/436

**Comment by bagage** [comment]
Hmm, for me it does not work when Eolie's width is larger than halfscreen.

If maximized and hitting `ctrl + shift + left arrow` -> does not work.
If 50% width and hitting `ctrl + shift + left arrow` -> does work
If 25% width and hitting `ctrl + shift + left arrow` -> does work
If 75% width and hitting `ctrl + shift + left arrow` -> does **not** work

**Comment by gnumdk** [comment]
Yes, it's because button + uri bar are larger than half screen.

**Comment by gnumdk** [comment]
I fixed it in Lollypop but for now, I don't remember why it works with lollypop (that is doing some complicated calculation between infobar and titlebar).

**Comment by gnumdk** [comment]
Fixed
