### ISSUE TITLE
Tabs sidebar overlaps webpage

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#55]
BUG MAY BE REJECTED IF MISSING:

### Environement
- Eolie version: git master 6907e92
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: debian unstable

### Bug/Feature
I think it's a recent regression, but the tabs sidebar overlaps the content view on my setup (see screenshot):
![capture d ecran de 2017-06-05 20-59-21](https://cloud.githubusercontent.com/assets/1451988/26798733/04beec72-4a32-11e7-9d99-076cd9196847.png)
Also few days ago I could choose this sidebar behaviour (icons only, full miniatures, etc.). This seems to have disappeared. Since I now build it from git master, this might be some dependency issue that explains that?

**Comment by bagage** [comment]
Regression - the issue went back.

**Comment by bagage** [comment]
Should I open another issue? I cannot reopen that one because I'm not the one who closed it :-/.

**Comment by gnumdk** [comment]
It's not possible, I'm not using an overlay since full minimal mode.

**Comment by bagage** [comment]
Well, it looks like the html document x position is still absolute to the window position and not relative to the sidebar: 

![capture d ecran de 2017-06-12 11-04-08](https://user-images.githubusercontent.com/1451988/27026739-10312714-4f5f-11e7-9a5d-71b1ed442ec3.png)

**Comment by gnumdk** [comment]
Are you sure you have uninstalled flatpak version? Looks like you are not using last git.

**Comment by bagage** [comment]
Hmm… both cannot live with each other? Indeed you are right but I don't get why flatpak version is being used - nor why they conflicts with each other. 
So basically you have to ensure the issue is present on flatpak version before reporting a bug, **but** you must uninstall it when you want to use the development version. Damn.

**Comment by gnumdk** [comment]
Or, you need to run /usr/local/bin/eolie ;)
