### ISSUE TITLE
Blank "popular websites" homepage

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#56]
### Environement
- Eolie version: git master 981e6e3
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: debian unstable

### Bug/Feature
It was working few days ago also, but now it seems the homepage with popular websites is blank on my PC. The only log I can see when (re)loading is: `Update zoom level: 100.0`.

**Comment by bagage** [comment]
The issue was that db-version was set to `1` instead of `0`. 
Not sure why and if there is anything to do, feel free to close directly if not :).

**Comment by gnumdk** [comment]
No the issue can't be that as db-version is not used in git master 981e6e3 ;)

**Comment by bagage** [comment]
Hmm, well the issue is strange and still present. After reinitializing dconf-editor to all default values for Eolie, I had some websites on the homepage that appeared.
However now only one is left (twitter) - even if I go at 50 websites.

Is there anything else than dconf configuration and $HOME/.local/share/Eolie data directory?

**Comment by gnumdk** [comment]
~/.cache/eolie

**Comment by bagage** [comment]
OK thanks. There is something wrong I believe:

I have 19 cached `_start.png` files in ~/.cache/eolie.
I have 19 "popular websites" retrieved from bookmarks.

Only twitter matches both side - all other generated cache files are for sites I visited only once?
I'll keep investigate this a bit.

**Comment by bagage** [comment]
Might be related:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/eolie/extension_proxy.py", line 344, in __on_send_request
    self.__bus.emit_signal(
AttributeError: 'NoneType' object has no attribute 'emit_signal'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/eolie/extension_proxy.py", line 344, in __on_send_request
    self.__bus.emit_signal(
AttributeError: 'NoneType' object has no attribute 'emit_signal'
```

**Comment by bagage** [comment]
OK found the issue: [the culprit is here](https://github.com/gnumdk/eolie/blob/master/src/stacksidebar_child.py#L124-L125). I'm running with "minimal" sidebar, so I never go in the snapshot saving if.
