### ISSUE TITLE
Cannot close Eolie single window via keyboard

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#57]
### Environement
- Eolie version: git master 981e6e3
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: debian unstable

### Bug/Feature
Sorry to reopen a bug about that :) it's a bit related with #38 but since `ctrl+w` does not close the last tab of a window and `ctrl+q` quits Eolie entirely, there is no way to close a single Eolie window (except by using the topcorner cross with mouse).

**Comment by gnumdk** [comment]
Alt + F4 ? You can change this shortcut in Gnome settings.

**Comment by bagage** [comment]
Oops, totally.
