### ISSUE TITLE
Allow ctrl+pageup and ctrl+pagedown for next/previous tab shortcuts?

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#58]
### Environement
- Eolie version: git master 981e6e3
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: debian unstable

### Bug/Feature
I believe next/previous tab shortcuts (`ctrl+tab` and `ctrl+shift+tab`) are used because the tabs list is vertical instead of horizontal and that these shortcuts can be used with left hand only.

However (at least with laptop and no mouse) both hands are on the keyboard and I feel it easier to use `ctrl+pageup` and `ctrl+pagedown` to change tab (besides it's the "standard"/expected shortcut for it).

If you think it would break design/you're against the idea of having two different shortcuts for the same thing, would it be possible to make these shortcuts modifiable (via dconf or ideally via the shortcut window one day once it supports it)? 
It would be awesome!

**Comment by gnumdk** [comment]
No, you are right, I need to respect both Gnome shortcuts and most browsers shortcuts.

**Comment by bagage** [comment]
Just as a side question: why your commits are 12 hours behind actual time? 

> 6c07885 2017-06-06 **00:05:07** +0200 Cédric Bellegarde       Fix #58
