### ISSUE TITLE
Double-clicking on the url bar should select the whole current url

### ISSUE THREAD

**Issue by cristobaltapia** [gnumdk/eolie#6]
I don't know if I am using the url bar in the wrong way, but it should work similar to every other web-browser, were a double-click on it should mark the whole text, so that one can start writing a new address.

**Comment by gnumdk** [comment]
@cristobaltapia Are you using Eolie? How do you feel with it? :)

**Comment by cristobaltapia** [comment]
Hi @gnumdk , yes I have used Eolie a bit, and I kind of like it. It has a nice clean interface and it works. The placement of tabs on the left is a bit strange at first, but then it is actually quite nice. I think it makes me be more aware of the tabs I currently have open (I don't know if that is something good though, maybe it has some distraction factor). But thinking on touchscreens, it is surely easier to target with the finger as the normal Firefox tabs. 
Regarding the color of the tabs-panel, I am not sure if it is good that it is white. Maybe it could have the color of the side-panel of nautilus (but arguing about colors is always a thing of personal taste :) ). 
It is also very nice how you managed to squeeze bookmarks, search and history in a popover in the url-bar. 

On the more personal-preferences side, I am a VimFX user in Firefox, so it is difficult for me to use the mouse to click links hahaha :P 

But very nice work! I will keep testing it and report issues.

**Comment by gnumdk** [comment]
Ok, thanks for information ;)
