### ISSUE TITLE
Ctrl+z not working in some textfields

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#61]
### Environement
- Eolie version: git master 981e6e3
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: debian unstable

### Bug/Feature
it may be related to Webkit but Ctrl+Z (cancel modifications) does not work on some website. 
For instance here (on **github**) Ctrl+z has no effect. Same thing on **phpBB forums**. (*NOK*)
But it works on some other websites (on **Twitter** for instance). (*OK*)

**Comment by gnumdk** [comment]
To be sure, test with epiphany, if you reproduce issue in epiphany, then it's a webkit bug ;)

**Comment by gnumdk** [comment]
Here it works in epiphany :)

**Comment by gnumdk** [comment]
But not in poseidon, strange...

**Comment by bagage** [comment]
It works in epiphany here too for both websites.

**Comment by gnumdk** [comment]
Ok, I think it's implemented by Twitter in js. So I need to implement this in Eolie.

**Comment by gnumdk** [comment]
ephy_web_extension_proxy_web_page_has_modified_forms() in epiphany so need to be implemented, next task :)

**Comment by gnumdk** [comment]
Not really working for now ;)

**Comment by gnumdk** [comment]
It's working now. And I fixed many issue implementing this feature ;)
