### ISSUE TITLE
User feedback when WebKit crashes?

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#62]
### Environement
- Eolie version: git master 345eb6c
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: debian unstable

### Bug/Feature

As a Geary developer I saw a lot of issues related to WebKit, I think there will be many more crashes in webkit here too, so do you think it could be interresting to have some user feedback when it crashes?

For instance by entering url of a website (can send it to you in private) in a new tab, Eolie starts loading… and quits the tab. As a developer I looked in the logs and saw that `WebViewErrors::__on_web_process_crashed(): <view_web.WebViewMeta object at 0x7fc23418d1f8 (WebKitWebView at 0x55c4bbdba620)>`. 
But it would be cool if:

1. somewhat a feedback is shown, like "Oops, this page crashed" similarly to what Chrome does:
![capture d ecran de 2017-06-07 10-46-22](https://user-images.githubusercontent.com/1451988/26869989-bd2a52b4-4b6e-11e7-8812-ce05ff8589fb.png)

2. ideally with a "[report a bug to Webkit](https://bugs.webkit.org/enter_bug.cgi)" link to their bugtracker, ideally with already set title "Crash when opening URL <current_url>"

PS: I love this project, thanks @gnumdk :).

**Comment by gnumdk** [comment]
Really cool idea, send me uri by mail
