### ISSUE TITLE
Previous tabs opened when opening link from external app

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#63]
### Environement
- Eolie version: git@345eb6c65b0db3e2f0d1f8825a58112e439b61ea
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Fedora 26 Alpha

### Bug
With `Remember previous previous pages on startup` checked and Eolie set as default browser on the system.
When I open a link from an other app on Eolie, Eolie open that link but also open previous session tabs.

**Comment by d9h02f** [comment]
Makes sense, no? What should happen instead?

**Comment by M5oul** [comment]
In fact, but I found that strange compared to Firefox behaviour.
Eolie behaviour restoration is also different as the new tab is open in up position compared to restored tabs.

**Comment by gnumdk** [comment]
Make sense for me, if Eolie restore 50 pages, you don't want to scroll down to your page, and I don't want auto scroll like feature.

**Comment by gnumdk** [comment]
What is Firefox behaviour?

**Comment by gnumdk** [comment]
Ok, I understand the issue ;)

**Comment by M5oul** [comment]
Thanks! Looks better now.
