### ISSUE TITLE
Missing usual shortcuts: F5, End, Home, Ctrl+H, Ctrl+B, Ctrl+K

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#65]
- Eolie version: git master 981e6e3
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: debian unstable
### Bug/Feature
Some standards shortcuts that are, imo, missing (forgot to mention them in #58):

1. F5 to refresh page
2. Home to go to the head of page
3. End for the opposite :).

There might be others but these are the ones I am thinking of right now.

**Comment by bagage** [comment]
Adding:

1. Ctrl+H: open history popover
2. Ctrl+B: open bookmarks popover
3. Hence maybe a third shortcut for the "search" popover as well?

**Comment by gnumdk** [comment]
Ctrl+K for search

**Comment by gnumdk** [comment]
Here home and end are working.
