### ISSUE TITLE
GNOME dark theme support

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#68]
### Environement
- Eolie version: 0.8 (freshly cloned from git)
- GNOME/GTK+ versions: GNOME 3.24.2, gtk+ 3.22.15
- GNU/Linux distribution: Fedora 26

### Bug/Feature

Although I have enabled the GNOME "global dark theme" in GNOME tweak tool, eolie is still using the light theme.

**Comment by gnumdk** [comment]
It works, something is broken in your configuration.

I guess you have flatpak and git version installed but you are running flatpak one (support global dark theme is not possible without installing gnome-tweak-tool via flatpak)

**Comment by Gwend4l** [comment]
oh yes indeed, I thought I had removed the flatpak but it looks like I was wrong... it does work perfectly!

sorry for the bug report! and btw very nice job with eolie :)
