### ISSUE TITLE
"About" pop up on one window also blocks other windows

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#69]
### Environment
- Eolie version: 0.8 (freshly cloned from git)
- GNOME/GTK+ versions: GNOME 3.24.2, gtk+ 3.22.15
- GNU/Linux distribution: Fedora 26

### Bug/Feature

When the about window is opened in one eolie window, the other eolie windows do not respond to any interactions (mouse, keyboard) any more.

**Comment by bagage** [comment]
I'm affraid there is the same issue for Shortcuts popup window and Preference one.

**Comment by gnumdk** [comment]
BTW, fix is not good as about dialog in nautilus is modal

**Comment by gnumdk** [comment]
Same behaviour in epiphany

**Comment by gnumdk** [comment]
Seems to be wanted by GTK. Works in nautilus because nautilus fork a process per window.
