### ISSUE TITLE
URl bar clears content after a few hundred ms

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#74]
### Environment
- Eolie version: git master cb9d769
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: debian unstable

### Bug/Feature
When you open a new tab and immediately start typing, you may encounter a bug where the URL bar is cleared after a small amount of time (~350ms). 
Similarly, if you try to paste something in the URL bar to fast after opening a new tab/window, it won't be pasted (focus is gained too late?).
Can be reproduced with shortcuts sequence: `ctrl+L / ctrl+C / ctrl+T or ctrl+N / ctrl+V`.

**Comment by gnumdk** [comment]
Just fixed. Was working on it without knowing this bug report :D

**Comment by bagage** [comment]
Awesome! You rock :+1:
