### ISSUE TITLE
Avoid destructive closing

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#75]
### Environment
- Eolie version: git master cb9d769
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: debian unstable

### Bug/Feature
Now that #61 is fixed, the remaining issue I can see is when you destroy the tab (via `alt+f4` - thanks #57 :) or via `ctrl+w` or `ctrl+q`), nothing warn you that you will lose your data.
I had to rewrite my bug report #74 three times because of this (hit ctrl+q instead of alt+f4 to close another window, hit alf+f4 instead of ctrl+w to close a single tab…).
Would be great to have `are you sure you want to lose your text` warning, if possible :).

**Comment by gnumdk** [comment]
Yes, was on my TODO list, thanks for report!
