### ISSUE TITLE
Bookmarks not Synced?

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#77]
### Environment
- Eolie version: 10bcf92
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Debian unstable

### Bug/Feature
I am using Firefox Sync to sync bookmarks and history, and while it works for history I have doubts for bookmarks.
When I hit `ctrl+B` (:)) I don't see any of them in any of the 3 available categories (popular / recent / unclassified). Should I look for them elsewhere or is this a bug?

**Comment by gnumdk** [comment]
Eolie translate "folder" to tags or use firefox tags if exist.

For recent, you are right, should be recently added, now it's recently opened.

**Comment by gnumdk** [comment]
But I just hit a big bug deleting all my eolie bookmarks. Fixing it as soon as possible.

**Comment by gnumdk** [comment]
Should be ok now.

**Comment by Gwend4l** [comment]
I have a problem as well with bookmarks: none of my firefox bookmarks are available in eolie. Yet it works the other way around: new eolie bookmarks appear in firefox.

And I think that it had worked at some point, very early in my eolie testing. I remember seing my huge list of firefox bookmarks in eolie. But now it's empty....

**Comment by gnumdk** [comment]
@Gwend4l rm -f ~/.local/share/eolie/mozilla_sync.bin

**Comment by Gwend4l** [comment]
I did that this morning and I restarted Eolie. At the moment the bookmarks from firefox still haven't appeared again in Eolie.

**Comment by gnumdk** [comment]
rm -f ~/.local/share/eolie/mozilla_sync.bin
then:
eolie -d

**Comment by Gwend4l** [comment]
Wow, lots of output when starting with `-d`.

So, while I was looking at the first listing of logs it created (with password and history sync only), it started spilling out logs again with the bookmark sync. For some reason, this time, bookmarks did reach Eolie, and everything seems there once again! 

Too bad I could not reproduce the issue. I'll let you know if they disappear once again.

**Comment by bagage** [comment]
i personally still have the issue even when removing `mozilla_sync.bin`. In logs I can see:

```
iTunes Application Detector This plug-in detects the presence of iTunes when opening iTunes Store URLs in a web page with Firefox. /usr/lib/mozilla/plugins/librhythmbox-itms-detection-plugin.so
Evince Browser Plugin The <a href="http://wiki.gnome.org/Apps/Evince/">Evince</a> 3.22.1 plugin handles documents inside the browser window. /usr/lib/mozilla/plugins/libevbrowserplugin.so
IcedTea-Web Plugin (using IcedTea-Web 1.6.2 (1.6.2-3.1)) The <a href="http://icedtea.classpath.org/wiki/IcedTea-Web">IcedTea-Web Plugin</a> executes Java applets. /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/IcedTeaPlugin.so
Shockwave Flash Shockwave Flash 24.0 r0 /usr/lib/flashplugin-nonfree/libflashplayer.so
GNOME Shell Integration This plugin provides integration with GNOME Shell for live extension enabling and disabling. It can be used only by extensions.gnome.org /usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so
Evince Browser Plugin The <a href="http://wiki.gnome.org/Apps/Evince/">Evince</a> 3.22.0 plugin handles documents inside the browser window. /usr/local/lib/mozilla/plugins/libevbrowserplugin.so
Update zoom level: 100.0
Start syncing
local passwords: 0.1, remote passwords: 1497259686.83
pull passwords
<PULLING PASSWORDS>
local history: 0.1, remote history: 1497295940.85
pull history
SettingsDialog::__on_clear_search(): g-dbus-error-quark: No such secret item at path: /org/freedesktop/secrets/collection/login/1042 (19)
** Message: Remote error from secret service: org.freedesktop.DBus.Error.UnknownMethod: L'interface « org.freedesktop.Secret.Item » n'existe pas pour l'objet à l'emplacement /org/freedesktop/secrets/collection/login/924
<PULLING HISTORY>
Update zoom level: 100.0
```

Error lines after `pull history` appear more than once. Nothing related to bookmarks. Using 432ad85.

**Comment by gnumdk** [comment]
Firefox is really doing strange things... Why the fuck do you have an empty bookmark???

**Comment by bagage** [comment]
Confirmed, this solves the bug. Cool!
