### ISSUE TITLE
Option for Ctrl+Tab cycles through tabs in recently used order

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#78]
### Feature request
Add an option for [Ctrl+Tab cycles through tabs in recently used order](http://techdows.com/2016/07/firefox-50-new-preference-ctrltab-cycles-through-tabs-in-recently-used-order.html)

**Comment by gnumdk** [comment]
Not sure about this one, tested feature in Firefox, really not fan of behaviour, find this really strange to use and unatural.

**Comment by gnumdk** [comment]
And as a GNOME fan, really not fan of too many options ;)

**Comment by gnumdk** [comment]
Available in "No panel mode" and only for this one: Because it makes sense.
