### ISSUE TITLE
[feature] Add option to be able to edit the URL directly when creating a tab? 

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#80]
### Feature

Currently, when a new tab is created (ctrl+t), it is required to use right after the "edit URL" shortcut (ctrl+l) to enter a URL or browse the history. In my case, it means I do ctrl+t,ctrl+l in a row 95% of the time.

In Firefox, Chrome or Epiphany, it is possible to directly start typing after ctrl+t, without having to press ctrl+l right after. I am personaly rather used to this standard behavior :).

Would you consider aligning Eolie with this standard behaviour, or at least add an option for it?

**Comment by gnumdk** [comment]
What is your new page option, here it works.

**Comment by Gwend4l** [comment]
Oh, I had not suspected at all that the "Empty page" choice implied the behavior that I described above, so I never thought of testing it! Sorry for overlooking this, I guess this was not intuitive to me.

thanks, nice work :)

**Comment by gnumdk** [comment]
No, it should work with empty :p

**Comment by gnumdk** [comment]
Ok, it works with empty, not when a search engine is shown, not the same with firefox?

**Comment by gnumdk** [comment]
Ok, behaviour not available in firefox...

**Comment by Gwend4l** [comment]
it works perfectly as I wanted with 'empty' (ie. no need to press ctrl+l), and that's all I need! I just had not thought of testing this behavior with 'empty'. That's why I closed :)
