### ISSUE TITLE
Pasting in the address bar

### ISSUE THREAD

**Issue by Maestroschan** [gnumdk/eolie#81]
### Environment
- Eolie version 0.8 (Flatpak)
- GNOME/GTK+ versions : 3.22
- GNU/Linux distribution : Debian Stretch

### Bug
When i paste an URL address in the bar and press "Return" or "Entrer", it doesn't work all the time
https://webmshare.com/JGxG7 (here i had to try twice only)

**Comment by gnumdk** [comment]
Someone else  able to reproduce, here it's not doing the same thing :-(

**Comment by Gwend4l** [comment]
I cannot reproduce either... maybe a gtk bug? :(

**Comment by gnumdk** [comment]
Not with flatpak, looks impossible as we are using the sames libs.

**Comment by Gwend4l** [comment]
OK, in fact I can reproduce the problem on a regular basis. I open a new tab, enter something (I think this may happen even when typing, not only with pasting), press enter, and nothing happens. I then have to press ctrl+l, and press enter again.  I am not using flatpak.

**Comment by gnumdk** [comment]
Debian too?

**Comment by Gwend4l** [comment]
Fedora 26, gtk3 3.22.15

**Comment by gnumdk** [comment]
Another screencast? That I may be able to reproduce.

**Comment by Gwend4l** [comment]
I'll try, but not easy, I still don't know how to reproduce it in a systemaric way

**Comment by gnumdk** [comment]
@Maestroschan Can you try to build eolie from source?

And run /usr/local/bin/eolie to test if issue is fixed.

**Comment by Gwend4l** [comment]
I have rebuilt from source, and so far I haven't encountered the bug. I'll keep you updated if it happens again.

**Comment by Gwend4l** [comment]
The problem occured to me again once or twice, despite your patch :(. Hard to get a screencast since it's (seemingly) not very deterministic, but I'll see what I can do.

**Comment by Maestroschan** [comment]
I have difficulties to build it on Debian (a problem of webkit version), but on my Ubuntu VM i build it and it works well, without the bug.

**Comment by gnumdk** [comment]
Really strange :-(

**Comment by gnumdk** [comment]
Ok, just happened for me: ArchLinux and GNOME 3.24.
