### ISSUE TITLE
Cannot click on videos on youtube

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#85]
### Environment
- Eolie version: 0469bf4
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Debian unstable

### Bug/Feature
On youtube, when clicking on video thumbnails on home page for instance, nothing happens as if NoScript blocked it or equivalent.
As a workaround you can use `right click -> open link` to open the video.

**Comment by gnumdk** [comment]
Can't reproduce.

**Comment by gnumdk** [comment]
Please test with flatpak version when not using last GTK stack  before reporting a bug ;)

**Comment by bagage** [comment]
Good to know, thanks.
However I have the same issue on flatpak version - when reading a video, clicking on other ones does not do anything - most of the clickable items do nothing actually, on the whole website.
Refreshing it solves the problem *sometimes* and for *some time*. This is the only site I had such issue for now (should tests other streaming websites though).

**Comment by gnumdk** [comment]
You should test with epiphany and if happens too report this to webkitgtk.

**Comment by bagage** [comment]
Sorry I didn't precised that: it works great on Epiphany. It seems only occuring with Eolie, and only with one version of youtube. Only the first version is not working:

![1](https://user-images.githubusercontent.com/1451988/27005953-7aa8bb66-4e29-11e7-8f70-690f0beb9a79.png)

The second one (default version) is working:

![2](https://user-images.githubusercontent.com/1451988/27005954-8148d276-4e29-11e7-96ef-6400a51a4156.png)

Not sure why there is 2 differents versions and don't know how to get the first one for you - only get it when I am connected with my account…

**Comment by gnumdk** [comment]
Can't get this youtube version, even connected. :-(

**Comment by bagage** [comment]
I've sent you an account with does have the issue by email.

**Comment by gnumdk** [comment]
Thanks I can reproduce but do not have any idea of what the hell is happening!

**Comment by gnumdk** [comment]
Thanks for the account, helped a lot!

**Comment by bagage** [comment]
Awesome, thanks for the quick fix :D.
