### ISSUE TITLE
[feature] Even more minimal tab bar, without animation, and with tooltips?

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#86]
### Feature

Currently, in minimal mode, the vertical bar with all the tabs has a small slide animation when moving the cursor over it. 

Would you consider having an even more minimal mode, where the minimal bar would not move when putting the cursor over it, and instead only show tooltips (with the titles) when hovering over the tabs ?

I am not very fond of stuff that move simply when hovering my mouse over it, but that's just my personal taste :)

**Comment by gnumdk** [comment]
Will not add another minimal mode, so the question is: Do I remove current minimal mode?

**Comment by Gwend4l** [comment]
Well I really love having simply the small icons on the left, without the previews. So personally, if there was only one single minimal mode, I would enjoy one of the following:
- a single minimal mode similar to what I describe above (no animations, tooltips)
- the current minimal mode, with an additional option (checkbox) to disable the hover animation

But again, my personal taste :)

**Comment by bagage** [comment]
I agree with @Gwend4l, I also feel disturbed by mouse-over animation when you move your mouse between multiple windows - I would also prefer the first choice proposed.

**Comment by gnumdk** [comment]
Animation can be disabled by disabling GTK animations in GNOME tweak tool

**Comment by gnumdk** [comment]
Testing option but when only in minimal panel, you can select page as there is the close button :-(

**Comment by gnumdk** [comment]
So it works by removing the close button:
- Middle click allow closing
- Or Ctrl + W

Is that enough?

**Comment by Gwend4l** [comment]
Removing the close button would be perfect for me, as I was getting more and more annoyed after having cliqued on it by mistake several times :). I already only close the windows with middle clock or with ctrl+w.

So the only solution is to disable animation at the system level? It's not possible to do that only in Eolie?

**Comment by Gwend4l** [comment]
I just tested, and it's perfect (for me)! many thanks!
