### ISSUE TITLE
[feature] Compatibility with https://extensions.gnome.org/?

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#87]
### Feature

Since eolie is a fancy web browser for the GNOME environment, would you consider someday investigating how to make eolie compatible with https://extensions.gnome.org/ for installing GNOME extensions?

On firefox it requires an extension, which must be this repo: https://github.com/nE0sIghT/chrome-gnome-shell-mirror

**Comment by gnumdk** [comment]
Here it works.

**Comment by gnumdk** [comment]
Byt will not work with flatpak, missing extension from org.gnome.Platform

**Comment by Gwend4l** [comment]
Oh, I had not enabled the plugins in the preferences. I does work perfectly! awesome!

I should stop creating bug/feature requests and ask you directly :D is there any irc/matrix/xmpp channel for eolie yet?
