### ISSUE TITLE
Dark theme: Current selected tab color

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#88]
### Environment
- Eolie version: 7987644
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Debian unstable

### Bug/Feature
It might be a GTK/theming issue instead, but not sure so I'll post it here: on dark theme, the current tab is highlighted with blue. On light theme, this is OK, but on dark theme it's almost impossible to see which is the selected tab:
![capture d ecran de 2017-06-10 22-44-38](https://user-images.githubusercontent.com/1451988/27006210-9292efb2-4e2e-11e7-8372-419ffafcb06f.png)

Is it possible to change this color?

**Comment by gnumdk** [comment]
No, request GTK devs, it's an issue in Adwaita GTK contrasts...

**Comment by bagage** [comment]
OK, was the most probable reason, thanks.

**Comment by gnumdk** [comment]
http://worldofgnome.org/how-to-hack-gnomes-adwaita-gtk-theme/

**Comment by bagage** [comment]
Thanks for the link. For anyone who might be interested, you must tweak the following CSS line from the Adwaita-dark theme:

```
@define-color theme_selected_bg_color #919dfc;
```
