### ISSUE TITLE
Hard seing text in input box on adwaita dark theme.

### ISSUE THREAD

**Issue by fyksen** [gnumdk/eolie#9]
![Like this](http://i.imgur.com/fJxVdRJ.png)

Now sure if this is a limitation of adwaita dark, or if it is Eolie

**Comment by Vistaus** [comment]
Hmm, isn't that just a dark theme issue in general? Because I remember seeing this problem in various browsers with all sorts of dark themes. I also vaguely remember that there's some sort of fix for Firefox (indicating that the problem is fixable).

**Comment by gnumdk** [comment]
It's an issue in WebKitGTK or GTK.
