### ISSUE TITLE
Downloading doesn't work in some cases

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#90]
### Environment
- Eolie version: d60c130462779697c3ce94c96b06fe0a274b6a3a
- GNOME/GTK+ versions: 3.24.32 / 3.22.15
- GNU/Linux distribution: Fedora 26

### Bug/Feature

When trying to download this file: 
https://link.springer.com/content/pdf/10.1007%2Fs10270-017-0598-5.pdf

nothing gets downloaded, while it works with firefox or wget.

**Comment by bagage** [comment]
I have also seen this seen this issue these days.

Related: if you open downloads list and click the "open folder" icon, it will/may/can crash. Note that it's rather random though and it depends of file being downloaded:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/eolie/popover_downloads.py", line 126, in __init__
    self.__label.set_label(destination.split("/")[-1])
AttributeError: 'NoneType' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/eolie/toolbar_end.py", line 183, in _on_download_button_toggled
    popover = DownloadsPopover()
  File "/usr/local/lib/python3.5/site-packages/eolie/popover_downloads.py", line 374, in __init__
    self.__populate()
  File "/usr/local/lib/python3.5/site-packages/eolie/popover_downloads.py", line 437, in __populate
    child = DownloadRow(download, False)
  File "/usr/local/lib/python3.5/site-packages/eolie/popover_downloads.py", line 128, in __init__
    self.__label.set_label(download.get_destination())
TypeError: Argument 1 does not allow None as a value
```

Your URL crashed the first time I opened it but after that it worked great (the PDF is displayed directly within Eolie which is nice BTW).

**Comment by Gwend4l** [comment]
Strange, in my case the PDF doesn't even open in Eolie!

But when clicking on the link, I indeed have the error `DownloadManager::__on_failed: WebKitDownloadError: Operation not supported (401)`.

**Comment by gnumdk** [comment]
@Gwend4l You are missing Evince web plugin. Will check by disabling it why this file is not downloaded.

**Comment by Gwend4l** [comment]
It seems to be installed though:

~~~
$ sudo dnf install evince-browser-plugin
Last metadata expiration check: 2:11:48 ago on Mon Jun 12 07:39:44 2017 CEST.
Package evince-browser-plugin-3.24.0-1.fc26.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
~~~

And I have the following in the logs, probably related: 
~~~
Error scanning plugin /usr/lib64/mozilla/plugins/libevbrowserplugin.so, /usr/libexec/webkit2gtk-4.0/WebKitPluginProcess returned 256 exit status
~~~

**Comment by gnumdk** [comment]
No, you need to enable plugins in Eolie in fact ;)
