### ISSUE TITLE
WebKitGTK doesn't update value for some inputs

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#92]
### Environment
- Eolie version: 2af469ee52a8d5240277afc3ff1d2da2bfc823db
- GNOME/GTK+ versions: GNOME 3.24.2, gtk+ 3.22.15
- GNU/Linux distribution: Fedora 26

### Bug/Feature

When going for instance on http://www.arretsurimages.net/chroniques/2017-06-12/Les-correspondants-etrangers-adorent-la-flexi-securite-id9949 , Eolie always suggests to store the password "Courriel / ****", before you enter any password by yourself. These forms are pre-filled by the website with these values, which must confuse Eolie.

**Comment by ebousse** [comment]
Thanks, this is much better now :D

One problem remains though: now, if I enter my login/password and submit, it suggests once again to store the password "Courriel / ****", instead of the login/password that I have entered for login in.

**Comment by gnumdk** [comment]
Yes need some more work.

**Comment by Gwend4l** [comment]
(Sorry, small mistake, I had commented with some wrong account, and I wanted to re-submit the comment with the correct account, bu by mistake I simply deleted it)

(In summary: with the current fix, it wants to store the password "Courriel / ****" with the example above, after logging in with real credentials)

**Comment by gnumdk** [comment]
Yes, that's a WebKitGTK issue.

Just look at web inspector (you can enable it in dconf-editor -> /org/gnome/Eolie), input value never changes on this page.

Do you think you can report issue upstream? (will save me time).

**Comment by gnumdk** [comment]
@Gwend4l ping? :)

**Comment by gnumdk** [comment]
https://bugs.webkit.org/show_bug.cgi?id=173653

**Comment by Gwend4l** [comment]
sorry for my lack of answer, I had put this on my todolist but was rather busy because of work :(

But note that I have recently opened 2 webkit tickets due to bugs I have found while browsing with Eolie, and I plan to submit even more. I was really accustomed to Firefox, and wow webit is really very buggy by comparison :)

**Comment by gnumdk** [comment]
No problem ;)
