### ISSUE TITLE
[feature] In bookmarks, provide a way to select many bookmarks easily?

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/eolie#94]
### Feature

In the bookmarks view, while it is possible to select multiple bookmarks one by one while holding ctrl, I could not find a way to select lots of bookmarks, such as:
- selecting all bookmarks between 2 bookmarks, eg. by holding ctrl+shift
- selecting all bookmarks within a given tag, eg. with ctrl+a

What would you think of such feature? Personally it would help me cleaning up bookmark more quickly, and I would enjoy drag-and-dropping many of them from one folder to another.

**Comment by gnumdk** [comment]
The Ctrl + Shift issue is an issue in GTK, can reproduce here with a simple Gtk.ListBox.

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=733108

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=749252
