### ISSUE TITLE
Allow removing bookmarks folder

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#96]
### Environment
- Eolie version: 0.8-72-g3874f3c
- GTK+ version: 3.22
- Operating system: Linux sessifet 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### Bug/Feature
Now that #77 is fixed, I'm trying to clean up these a bit. 
Would be great (not a major issue though) if we could remove a bookmarks folder somehow. For now I'm opening it, hit `ctrl`, select first item, hit `shift`, select last item and hit the trashbin in bottom bar. It seems it makes the folder disappears, but it's not very confortable.

**Comment by gnumdk** [comment]
It's not a folder, it's a tag, just remove the tag in the bookmark editor...
Will not add such feature.

**Comment by bagage** [comment]
Fair enough, but what exactly are you calling the bookmark editor?

**Comment by gnumdk** [comment]
When you edit a bookmark?

**Comment by bagage** [comment]
Oh! Never opened it before :). Thanks :D.
